package com.lastdom.game;

import android.app.Activity;
import android.os.Bundle;
import android.content.*;
import android.graphics.*;
import android.view.*;
import android.os.Handler;
import java.util.*;

public class MainActivity extends Activity {
    GameView view;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);view=new GameView(this);setContentView(view);}
    @Override protected void onPause(){super.onPause();view.save();}

    static class Survivor {String name,role,job="Отдых";int skill,health=100,hunger=10,fatigue=10,morale=75;boolean alive=true;Survivor(String n,String r,int s){name=n;role=r;skill=s;}}
    static class Location {String name,type;int distance,risk,stock;boolean discovered;Location(String n,String t,int d,int r,int st,boolean seen){name=n;type=t;distance=d;risk=r;stock=st;discovered=seen;}}

    class GameView extends View {
        Paint p=new Paint(3),stroke=new Paint(3);Random rnd=new Random();Handler timer=new Handler();SharedPreferences sp;
        ArrayList<Survivor> people=new ArrayList<>();ArrayList<String> log=new ArrayList<>();ArrayList<Location> locations=new ArrayList<>();
        String[] jobs={"Отдых","Еда","Вода","Материалы","Ремонт","Охрана","Лечение"};
        String[] rooms={"Генераторная","Кухня","Медпункт","Мастерская","Баррикады","Спальня"};
        String[] roomJobs={"Ремонт","Еда","Лечение","Материалы","Охрана","Отдых"};
        int[] roomLevels={1,1,1,1,1,1},roomCondition={100,100,100,100,100,100};
        int day=1,gameMinute=480,speed=1,food=28,water=34,power=24,mats=18,threat=12,shelter=100,selected=-1,selectedRoom=-1,screen=0,buildingRoom=-1,buildRemaining=0;
        boolean paused=false,event=false,gameOver=false,jobMenu=false;String eventTitle="",eventText="";String[] eventChoices=new String[2];
        int expeditionPerson=-1, expeditionLocation=-1, expeditionRemaining=0, selectedLocation=-1; boolean expeditionEvent=false;
        int W,H;float scale=1f;
        int bg=Color.rgb(14,16,20),panel=Color.rgb(28,31,37),panel2=Color.rgb(40,44,51),text=Color.rgb(238,234,224),muted=Color.rgb(166,166,160),accent=Color.rgb(213,143,70),danger=Color.rgb(190,72,65),good=Color.rgb(101,160,104),blue=Color.rgb(88,132,166);
        GameView(Context c){super(c);sp=getSharedPreferences("save_v02",0);initLocations();load();timer.postDelayed(tick,1000);}
        void initLocations(){locations.clear();locations.add(new Location("Продуктовый","еда / вода",2,12,100,true));locations.add(new Location("Аптека","медицина",3,18,100,true));locations.add(new Location("Гаражи","материалы",4,24,100,true));locations.add(new Location("Соседний дом","разное",5,30,100,true));locations.add(new Location("Склад","крупная добыча",7,42,100,false));locations.add(new Location("Больница","редкие припасы",9,55,100,false));}
        Runnable tick=new Runnable(){public void run(){if(!paused&&!gameOver&&!event){for(int i=0;i<speed;i++)advanceMinute();invalidate();}timer.postDelayed(this,1000);}};
        Survivor make(String n,String r,int s){return new Survivor(n,r,s);}void defaults(){people.clear();people.add(make("Иван","Инженер",4));people.add(make("Мария","Врач",4));people.add(make("Сергей","Охрана",4));people.add(make("Анна","Сборщик",3));people.add(make("Павел","Механик",4));}
        void reset(){day=1;gameMinute=480;speed=1;paused=false;food=28;water=34;power=24;mats=18;threat=12;shelter=100;selected=-1;selectedRoom=-1;screen=0;buildingRoom=-1;buildRemaining=0;roomLevels=new int[]{1,1,1,1,1,1};roomCondition=new int[]{100,100,100,100,100,100};event=false;gameOver=false;jobMenu=false;expeditionPerson=-1;expeditionLocation=-1;expeditionRemaining=0;selectedLocation=-1;initLocations();defaults();log.clear();addLog("Убежище готово. Дом оживает.");save();invalidate();}
        void advanceMinute(){gameMinute++;if(expeditionPerson>=0){expeditionRemaining--;if(expeditionRemaining<=0)finishExpedition();}if(buildingRoom>=0){buildRemaining--;if(buildRemaining<=0){roomLevels[buildingRoom]++;roomCondition[buildingRoom]=100;addLog(rooms[buildingRoom]+" улучшена до ур. "+roomLevels[buildingRoom]+".");buildingRoom=-1;}}if(gameMinute>=1440){gameMinute=0;day++;dailyCycle();}if(gameMinute%60==0)save();}
        String clock(){return String.format(Locale.getDefault(),"%02d:%02d",gameMinute/60,gameMinute%60);}String phase(){int h=gameMinute/60;return h>=6&&h<12?"УТРО":h>=12&&h<18?"ДЕНЬ":h>=18&&h<22?"ВЕЧЕР":"НОЧЬ";}
        void dailyCycle(){processJobs();int a=aliveCount();food=Math.max(0,food-a);water=Math.max(0,water-a*2);power=Math.max(0,power-Math.max(1,1+roomLevels[0]/2));threat=Math.min(100,threat+2+rnd.nextInt(4));for(int i=0;i<6;i++)roomCondition[i]=Math.max(15,roomCondition[i]-(1+rnd.nextInt(3)));for(Survivor s:people)if(s.alive){s.hunger=Math.min(100,s.hunger+10);if(food==0||water==0)s.health=Math.max(0,s.health-6);if(s.health<=0){s.alive=false;addLog(s.name+" погиб.");}}if(aliveCount()==0||shelter<=0)gameOver=true;else if(rnd.nextInt(100)<45)triggerEvent();else addLog("Новый день начался спокойно.");save();}
        int aliveCount(){int n=0;for(Survivor s:people)if(s.alive)n++;return n;}void addLog(String s){log.add(0,"День "+day+" • "+clock()+": "+s);while(log.size()>35)log.remove(log.size()-1);}
        void save(){SharedPreferences.Editor e=sp.edit();e.putInt("day",day).putInt("gameMinute",gameMinute).putInt("speed",speed).putBoolean("paused",paused).putInt("buildingRoom",buildingRoom).putInt("buildRemaining",buildRemaining).putInt("food",food).putInt("water",water).putInt("power",power).putInt("mats",mats).putInt("threat",threat).putInt("shelter",shelter).putInt("count",people.size());for(int i=0;i<people.size();i++){Survivor s=people.get(i);String k="p"+i+"_";e.putString(k+"name",s.name).putString(k+"role",s.role).putString(k+"job",s.job).putInt(k+"skill",s.skill).putInt(k+"health",s.health).putInt(k+"hunger",s.hunger).putInt(k+"fatigue",s.fatigue).putInt(k+"morale",s.morale).putBoolean(k+"alive",s.alive);}for(int i=0;i<6;i++){e.putInt("room"+i,roomLevels[i]);e.putInt("roomCond"+i,roomCondition[i]);}e.putInt("expPerson",expeditionPerson).putInt("expLoc",expeditionLocation).putInt("expRemain",expeditionRemaining);for(int i=0;i<locations.size();i++){e.putInt("locStock"+i,locations.get(i).stock);e.putBoolean("locSeen"+i,locations.get(i).discovered);}e.putString("log",android.text.TextUtils.join("\n§\n",log));e.apply();}
        void load(){if(!sp.contains("day")){reset();return;}day=sp.getInt("day",1);gameMinute=sp.getInt("gameMinute",480);speed=sp.getInt("speed",1);paused=sp.getBoolean("paused",false);buildingRoom=sp.getInt("buildingRoom",-1);buildRemaining=sp.getInt("buildRemaining",0);food=sp.getInt("food",28);water=sp.getInt("water",34);power=sp.getInt("power",24);mats=sp.getInt("mats",18);threat=sp.getInt("threat",12);shelter=sp.getInt("shelter",100);expeditionPerson=sp.getInt("expPerson",-1);expeditionLocation=sp.getInt("expLoc",-1);expeditionRemaining=sp.getInt("expRemain",0);for(int i=0;i<locations.size();i++){locations.get(i).stock=sp.getInt("locStock"+i,100);locations.get(i).discovered=sp.getBoolean("locSeen"+i,locations.get(i).discovered);}for(int i=0;i<6;i++){roomLevels[i]=sp.getInt("room"+i,1);roomCondition[i]=sp.getInt("roomCond"+i,100);}int n=sp.getInt("count",5);people.clear();for(int i=0;i<n;i++){String k="p"+i+"_";Survivor s=make(sp.getString(k+"name","Выживший"),sp.getString(k+"role","Житель"),sp.getInt(k+"skill",2));s.job=sp.getString(k+"job","Отдых");s.health=sp.getInt(k+"health",100);s.hunger=sp.getInt(k+"hunger",10);s.fatigue=sp.getInt(k+"fatigue",10);s.morale=sp.getInt(k+"morale",75);s.alive=sp.getBoolean(k+"alive",true);people.add(s);}String l=sp.getString("log","");if(!l.isEmpty())log.addAll(Arrays.asList(l.split("\\n§\\n")));}
        float sy(float y){return y*scale;}void txt(Canvas c,String s,float x,float y,float size,int col){p.setStyle(Paint.Style.FILL);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));p.setTextSize(sy(size));p.setColor(col);c.drawText(s,sy(x),sy(y),p);}void bold(Canvas c,String s,float x,float y,float size,int col){p.setStyle(Paint.Style.FILL);p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setTextSize(sy(size));p.setColor(col);c.drawText(s,sy(x),sy(y),p);}void box(Canvas c,float l,float t,float r,float b,int col,float rad){p.setStyle(Paint.Style.FILL);p.setColor(col);c.drawRoundRect(sy(l),sy(t),sy(r),sy(b),sy(rad),sy(rad),p);}void bar(Canvas c,float l,float t,float r,float h,int v,int col){box(c,l,t,r,t+h,Color.rgb(52,55,61),4);box(c,l,t,l+(r-l)*Math.max(0,Math.min(100,v))/100f,t+h,col,4);}
        @Override protected void onDraw(Canvas c){W=getWidth();H=getHeight();scale=W/420f;c.drawColor(bg);if(screen==0)drawMain(c);else if(screen==1)drawSurvivor(c);else if(screen==2)drawJournal(c);else if(screen==3)drawRooms(c);else if(screen==4)drawRoomDetail(c);else drawMap(c);if(event)drawEvent(c);if(jobMenu)drawJobMenu(c);if(gameOver)drawGameOver(c);}
        void drawHeader(Canvas c,String sub){bold(c,"ПОСЛЕДНИЙ ДОМ",20,30,20,text);txt(c,sub,20,49,11,muted);box(c,250,12,400,52,panel2,9);bold(c,"Д"+day+"  "+clock(),264,31,12,text);txt(c,phase(),264,46,9,phase().equals("НОЧЬ")?blue:accent);}
        void drawMain(Canvas c){drawHeader(c,"убежище • v0.6");drawResources(c);drawAtmosphere(c,116,438);drawCutaway(c,125,false);drawPeople(c,450);float y=H/scale-120;box(c,20,y,400,y+42,expeditionPerson>=0?panel2:accent,10);bold(c,expeditionPerson>=0?"ЭКСПЕДИЦИЯ • "+formatBuild(expeditionRemaining):"ВЫЙТИ В ГОРОД",expeditionPerson>=0?88:125,y+27,11,expeditionPerson>=0?text:Color.rgb(30,27,23));drawNav(c);}
        void drawResources(Canvas c){String[] a={"ЕДА "+food,"ВОДА "+water,"ЭН. "+power,"МАТ. "+mats};for(int i=0;i<4;i++){float x=20+i*96;box(c,x,68,x+88,108,panel,10);bold(c,a[i],x+12,92,10,text);}}
        int sky(){int h=gameMinute/60;if(h>=6&&h<12)return Color.rgb(78,75,70);if(h<18)return Color.rgb(72,82,88);if(h<22)return Color.rgb(66,47,51);return Color.rgb(18,23,34);}
        void drawAtmosphere(Canvas c,float top,float bottom){int h=gameMinute/60; if(h>=22||h<6){p.setColor(Color.rgb(214,218,207));c.drawCircle(sy(345),sy(top+32),sy(15),p);p.setColor(sky());c.drawCircle(sy(351),sy(top+27),sy(14),p);}else{p.setColor(Color.rgb(205,164,91));c.drawCircle(sy(345),sy(top+32),sy(13),p);}p.setStrokeWidth(sy(1));p.setColor(Color.argb(65,190,205,215));for(int i=0;i<18;i++){float x=18+((i*67+gameMinute*3)%385),y=top+((i*43+gameMinute*2)%Math.max(1,(int)(bottom-top)));c.drawLine(sy(x),sy(y),sy(x-5),sy(y+13),p);}}
        void drawCutaway(Canvas c,float top,boolean large){float left=20,right=400,height=large?500:305;box(c,left,top,right,top+height,Color.rgb(20,22,25),14);p.setColor(sky());c.drawRect(sy(left+7),sy(top+7),sy(right-7),sy(top+height-7),p);drawRuins(c,left+7,top+7,right-7,top+height-7);float bx=large?42:55,by=top+(large?38:28),bw=large?336:310,rh=large?136:82;p.setColor(Color.rgb(48,43,39));c.drawRect(sy(bx-8),sy(by-12),sy(bx+bw+8),sy(by+rh*3+6),p);for(int i=0;i<6;i++){int row=i/2,col=i%2;float l=bx+col*bw/2,t=by+row*rh,r=l+bw/2,b=t+rh;drawRoom(c,i,l,t,r,b,large);}p.setColor(Color.rgb(28,27,25));c.drawRect(sy(bx+bw/2-3),sy(by),sy(bx+bw/2+3),sy(by+rh*3),p);txt(c,"Нажмите на комнату • жители работают внутри",34,top+height-13,10,muted);}
        void drawRuins(Canvas c,float l,float t,float r,float b){p.setColor(Color.rgb(30,32,34));for(int i=0;i<7;i++){float x=l+i*62;float hh=24+(i%3)*17;c.drawRect(sy(x),sy(b-hh),sy(Math.min(r,x+45)),sy(b),p);for(int w=0;w<2;w++){p.setColor(Color.rgb(69,61,48));c.drawRect(sy(x+8+w*18),sy(b-hh+9),sy(x+13+w*18),sy(b-hh+15),p);p.setColor(Color.rgb(30,32,34));}}}
        void drawRoom(Canvas c,int i,float l,float t,float r,float b,boolean large){int base=roomCondition[i]<40?Color.rgb(70,43,40):Color.rgb(62,57,50);p.setColor(base);c.drawRect(sy(l+2),sy(t+2),sy(r-2),sy(b-2),p);p.setColor(Color.rgb(38,35,32));c.drawRect(sy(l+2),sy(t+2),sy(r-2),sy(t+7),p);p.setColor(Color.rgb(103,84,63));c.drawRect(sy(l+2),sy(b-12),sy(r-2),sy(b-2),p);boolean lit=power>0&&(gameMinute/60>=18||gameMinute/60<7);if(lit){p.setColor(Color.argb(75,240,185,82));c.drawCircle(sy((l+r)/2),sy(t+18),sy((r-l)*.34f),p);p.setColor(Color.rgb(224,174,79));c.drawCircle(sy((l+r)/2),sy(t+11),sy(4),p);}drawRoomIcon(c,i,(l+r)/2,t+(b-t)*.49f,large?1.25f:.8f);drawOccupantSprites(c,i,l,t,r,b,large);bold(c,rooms[i],l+8,b-27,large?11:9,text);txt(c,"УР."+roomLevels[i]+" • "+roomCondition[i]+"%",l+8,b-14,large?9:8,roomCondition[i]<40?danger:muted);if(buildingRoom==i){p.setColor(Color.argb(175,20,20,20));c.drawRect(sy(l+2),sy(t+2),sy(r-2),sy(b-2),p);bold(c,"🔨 СТРОЙКА",l+12,t+25,10,good);txt(c,formatBuild(buildRemaining),l+12,t+42,9,text);}}
        void drawOccupantSprites(Canvas c,int ri,float l,float t,float r,float b,boolean large){ArrayList<Survivor> here=new ArrayList<>();for(Survivor s:people)if(s.alive&&s.job.equals(roomJobs[ri])&&!s.job.equals("Экспедиция"))here.add(s);int n=Math.min(3,here.size());for(int j=0;j<n;j++){float x=r-18-j*(large?25:18),y=b-(large?48:38);drawPersonSprite(c,here.get(j),x,y,large?1f:.72f);}}
        void drawPersonSprite(Canvas c,Survivor s,float x,float y,float z){int cloth=s.role.equals("Врач")?Color.rgb(178,184,177):s.role.equals("Охрана")?Color.rgb(74,84,72):s.role.equals("Сборщик")?Color.rgb(102,82,61):Color.rgb(76,91,96);p.setColor(Color.rgb(196,158,125));c.drawCircle(sy(x),sy(y-15*z),sy(5*z),p);p.setColor(cloth);c.drawRoundRect(sy(x-6*z),sy(y-10*z),sy(x+6*z),sy(y+7*z),sy(3*z),sy(3*z),p);p.setStrokeWidth(sy(2*z));p.setColor(Color.rgb(35,33,31));c.drawLine(sy(x-3*z),sy(y+7*z),sy(x-5*z),sy(y+16*z),p);c.drawLine(sy(x+3*z),sy(y+7*z),sy(x+5*z),sy(y+16*z),p);}
        void drawRoomIcon(Canvas c,int i,float x,float y,float z){p.setStyle(Paint.Style.FILL);if(i==0){p.setColor(Color.rgb(70,83,84));c.drawRoundRect(sy(x-31*z),sy(y-17*z),sy(x+31*z),sy(y+19*z),sy(4*z),sy(4*z),p);p.setColor(Color.rgb(31,35,35));for(int q=-1;q<=1;q++)c.drawCircle(sy(x+q*17*z),sy(y+2*z),sy(7*z),p);p.setColor(accent);c.drawCircle(sy(x),sy(y+2*z),sy(4*z),p);p.setColor(Color.rgb(113,96,65));c.drawRect(sy(x-35*z),sy(y+19*z),sy(x+35*z),sy(y+23*z),p);}else if(i==1){p.setColor(Color.rgb(110,82,59));c.drawRect(sy(x-34*z),sy(y),sy(x+34*z),sy(y+18*z),p);p.setColor(Color.rgb(72,76,73));c.drawRect(sy(x-25*z),sy(y-24*z),sy(x+1*z),sy(y),p);p.setColor(Color.rgb(137,55,42));c.drawCircle(sy(x+18*z),sy(y-6*z),sy(7*z),p);p.setColor(Color.rgb(180,166,127));for(int q=0;q<3;q++)c.drawRect(sy(x-30*z+q*12*z),sy(y-8*z),sy(x-24*z+q*12*z),sy(y-2*z),p);}else if(i==2){p.setColor(Color.rgb(164,162,149));c.drawRect(sy(x-32*z),sy(y),sy(x+32*z),sy(y+15*z),p);p.setColor(Color.rgb(205,201,181));c.drawRect(sy(x-27*z),sy(y-8*z),sy(x+12*z),sy(y+3*z),p);p.setColor(danger);c.drawRect(sy(x+18*z),sy(y-25*z),sy(x+24*z),sy(y-7*z),p);c.drawRect(sy(x+12*z),sy(y-19*z),sy(x+30*z),sy(y-13*z),p);}else if(i==3){p.setColor(Color.rgb(108,74,51));c.drawRect(sy(x-35*z),sy(y),sy(x+35*z),sy(y+12*z),p);p.setColor(Color.rgb(124,128,126));c.drawRect(sy(x-22*z),sy(y-15*z),sy(x+20*z),sy(y-7*z),p);p.setColor(Color.rgb(68,69,67));c.drawCircle(sy(x+23*z),sy(y-11*z),sy(8*z),p);p.setStrokeWidth(sy(2*z));c.drawLine(sy(x-27*z),sy(y-19*z),sy(x-12*z),sy(y-5*z),p);}else if(i==4){p.setColor(Color.rgb(96,78,56));for(int q=-1;q<=1;q++)c.drawRect(sy(x-37*z),sy(y+q*12*z),sy(x+37*z),sy(y+(q*12+7)*z),p);p.setColor(Color.rgb(74,74,69));for(int q=-1;q<=1;q++)c.drawCircle(sy(x+q*25*z),sy(y+3*z),sy(3*z),p);}else{p.setColor(Color.rgb(100,79,66));c.drawRect(sy(x-35*z),sy(y),sy(x+35*z),sy(y+16*z),p);p.setColor(Color.rgb(174,160,136));c.drawRect(sy(x-30*z),sy(y-9*z),sy(x-5*z),sy(y+1*z),p);c.drawRect(sy(x+4*z),sy(y-9*z),sy(x+29*z),sy(y+1*z),p);p.setColor(Color.rgb(68,58,52));c.drawRect(sy(x-36*z),sy(y+16*z),sy(x+36*z),sy(y+20*z),p);}}
        String occupants(int ri){StringBuilder s=new StringBuilder();for(Survivor q:people)if(q.alive&&q.job.equals(roomJobs[ri])){if(s.length()>0)s.append(",");s.append(q.name);}return s.length()==0?"—":s.toString();}
        void drawPeople(Canvas c,float y){bold(c,"ЖИТЕЛИ",20,y,16,text);int max=Math.min(people.size(),5);for(int i=0;i<max;i++){Survivor s=people.get(i);float t=y+12+i*50;box(c,20,t,400,t+44,s.alive?panel:Color.rgb(48,31,32),9);p.setColor(Color.rgb(50,53,57));c.drawCircle(sy(43),sy(t+22),sy(15),p);drawPersonSprite(c,s,43,t+24,.65f);bold(c,s.name,68,t+18,12,text);txt(c,s.alive?s.role+" • "+s.job:"ПОГИБ",68,t+34,9,s.alive?muted:danger);bar(c,292,t+10,382,5,s.health,good);txt(c,"❤ "+s.health+"   ☺ "+s.morale,292,t+33,8,muted);}}
        void drawNav(Canvas c){float y=H/scale-66;box(c,16,y,404,y+50,panel,12);String[] n={"ДОМ","ЖУРНАЛ","КОМНАТЫ",paused?"▶":"×"+speed};for(int i=0;i<4;i++){float x=18+i*96;if(i==3)box(c,x+2,y+4,x+92,y+46,accent,9);bold(c,n[i],x+15,y+30,10,i==3?Color.rgb(30,27,23):text);}}
        void drawRooms(Canvas c){drawHeader(c,"интерактивный разрез");drawCutaway(c,75,true);bottomBack(c);}
        void drawRoomDetail(Canvas c){int i=selectedRoom;drawHeader(c,rooms[i]+" • уровень "+roomLevels[i]);box(c,20,75,400,285,panel,16);drawRoom(c,i,38,92,382,267,true);bold(c,"СОСТОЯНИЕ",24,320,12,muted);bar(c,24,330,396,10,roomCondition[i],roomCondition[i]<40?danger:good);txt(c,"Работают: "+occupants(i),24,365,12,text);txt(c,"Назначение: "+roomJobs[i],24,390,11,muted);String bonus=roomBonus(i);wrap(c,bonus,24,425,396,11,muted,17);int cost=6+roomLevels[i]*4;int time=120+roomLevels[i]*90;if(buildingRoom==i){box(c,24,490,396,548,panel2,12);bold(c,"УЛУЧШЕНИЕ ИДЁТ",42,514,12,good);txt(c,"Осталось "+formatBuild(buildRemaining),42,535,11,text);}else{box(c,24,490,396,548,accent,12);bold(c,"УЛУЧШИТЬ • "+cost+" МАТ.",42,514,12,Color.rgb(30,27,23));txt(c,"Время: "+formatBuild(time),42,535,10,Color.rgb(50,42,34));}box(c,24,560,396,612,panel2,12);bold(c,"НАЗНАЧИТЬ ЖИТЕЛЯ",42,592,12,text);bottomBack(c);}
        String roomBonus(int i){String[] a={"Стабилизирует энергоснабжение. Более высокий уровень снижает риск поломок.","Повышает эффективность запасов еды и работу повара.","Ускоряет восстановление здоровья и лечение травм.","Повышает добычу материалов и скорость технических работ.","Снижает угрозу нападений и ущерб дому.","Ускоряет отдых, снижает усталость и поддерживает мораль."};return a[i];}
        void drawMap(Canvas c){drawHeader(c,"карта разрушенного района");float top=68,bottom=H/scale-82;box(c,18,top,402,bottom,Color.rgb(31,34,35),14);p.setColor(Color.rgb(46,48,47));for(int i=0;i<8;i++){float yy=top+35+i*62;c.drawRect(sy(25),sy(yy),sy(395),sy(yy+5),p);}for(int i=0;i<6;i++){float xx=42+i*65;c.drawRect(sy(xx),sy(top+10),sy(xx+4),sy(bottom-8),p);}float hx=210,hy=top+150;drawMapNode(c,hx,hy,"ДОМ",true,0);float[][] pos={{90,top+78},{315,top+86},{92,top+245},{322,top+235},{132,top+370},{300,top+385}};for(int i=0;i<locations.size();i++){Location l=locations.get(i);float x=pos[i][0],y=pos[i][1];p.setStrokeWidth(sy(2));p.setColor(Color.rgb(76,74,67));c.drawLine(sy(hx),sy(hy),sy(x),sy(y),p);drawMapNode(c,x,y,l.discovered?l.name:"?",l.discovered,l.risk);if(l.discovered){txt(c,l.distance+" км",x-18,y+31,8,muted);bar(c,x-30,y+37,x+30,4,l.stock,l.stock<30?danger:good);}}txt(c,"Нажмите на точку, чтобы отправить свободного жителя",30,bottom-18,9,muted);if(expeditionPerson>=0){box(c,30,bottom-70,390,bottom-34,panel2,9);bold(c,"В ПУТИ • "+people.get(expeditionPerson).name,44,bottom-50,10,accent);txt(c,formatBuild(expeditionRemaining),320,bottom-50,10,text);}bottomBack(c);}
        void drawMapNode(Canvas c,float x,float y,String name,boolean seen,int risk){p.setColor(seen?(risk>40?Color.rgb(106,62,56):Color.rgb(78,84,75)):Color.rgb(45,47,48));c.drawCircle(sy(x),sy(y),sy(22),p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(sy(2));p.setColor(seen?accent:muted);c.drawCircle(sy(x),sy(y),sy(22),p);p.setStyle(Paint.Style.FILL);if(name.equals("ДОМ")){p.setColor(Color.rgb(135,111,79));c.drawRect(sy(x-10),sy(y-7),sy(x+10),sy(y+10),p);Path q=new Path();q.moveTo(sy(x-14),sy(y-7));q.lineTo(sy(x),sy(y-18));q.lineTo(sy(x+14),sy(y-7));q.close();c.drawPath(q,p);}bold(c,name,x-Math.min(35,name.length()*3.2f),y-28,8,seen?text:muted);}
        void drawLocationDialog(Canvas c,int li){ }
        int availableExplorer(){for(int i=0;i<people.size();i++)if(people.get(i).alive&&!people.get(i).job.equals("Экспедиция"))return i;return -1;}
        void startExpedition(int li){if(expeditionPerson>=0){addLog("Сначала дождитесь возвращения текущей экспедиции.");return;}Location l=locations.get(li);if(!l.discovered)return;int pi=availableExplorer();if(pi<0){addLog("Нет свободного жителя для вылазки.");return;}expeditionPerson=pi;expeditionLocation=li;expeditionRemaining=90+l.distance*35;people.get(pi).job="Экспедиция";addLog(people.get(pi).name+" отправился: "+l.name+". Возвращение через "+formatBuild(expeditionRemaining)+".");save();invalidate();}
        void finishExpedition(){if(expeditionPerson<0||expeditionLocation<0)return;Survivor s=people.get(expeditionPerson);Location l=locations.get(expeditionLocation);int night=(gameMinute/60>=22||gameMinute/60<6)?12:0;int risk=Math.min(85,l.risk+night);boolean hurt=rnd.nextInt(100)<risk;int stockFactor=Math.max(20,l.stock);int gain=1+rnd.nextInt(Math.max(2,stockFactor/18));if(l.name.equals("Продуктовый")){food+=gain+3;water+=gain+2;}else if(l.name.equals("Аптека")){s.health=Math.min(100,s.health+8);mats+=gain;}else if(l.name.equals("Гаражи")){mats+=gain+4;}else if(l.name.equals("Склад")){food+=gain;water+=gain;mats+=gain+5;}else if(l.name.equals("Больница")){mats+=gain+3;s.health=Math.min(100,s.health+15);}else{food+=gain;water+=gain;mats+=Math.max(1,gain/2);}l.stock=Math.max(0,l.stock-(8+rnd.nextInt(13)));if(hurt){int dmg=8+rnd.nextInt(20);s.health=Math.max(1,s.health-dmg);addLog(s.name+" вернулся раненым из "+l.name+" (-"+dmg+" здоровья). ");}else addLog(s.name+" вернулся из "+l.name+" с припасами.");s.job="Отдых";s.fatigue=Math.min(100,s.fatigue+22);if(rnd.nextInt(100)<35){for(Location q:locations)if(!q.discovered){q.discovered=true;addLog("Открыта новая точка: "+q.name+".");break;}}expeditionPerson=-1;expeditionLocation=-1;expeditionRemaining=0;save();}
        void drawSurvivor(Canvas c){Survivor s=people.get(selected);drawHeader(c,s.name+" • "+s.role);box(c,20,90,400,350,panel,16);bold(c,s.name,45,135,25,text);txt(c,s.role+" • навык "+s.skill,45,160,12,accent);txt(c,"Здоровье "+s.health+"%",45,205,12,text);bar(c,45,215,370,9,s.health,good);txt(c,"Голод "+s.hunger+"%   Усталость "+s.fatigue+"%",45,255,11,muted);txt(c,"Мораль "+s.morale+"%",45,285,11,muted);txt(c,"Сейчас: "+s.job,45,320,12,accent);box(c,35,390,385,448,accent,12);bold(c,"ИЗМЕНИТЬ РАБОТУ",105,425,13,Color.rgb(30,27,23));bottomBack(c);}
        void drawJournal(Canvas c){drawHeader(c,"журнал событий");float y=90;for(int i=0;i<Math.min(log.size(),10);i++){wrap(c,log.get(i),24,y,396,10,i==0?text:muted,15);y+=48;}bottomBack(c);}
        void bottomBack(Canvas c){float y=H/scale-65;box(c,20,y,400,y+48,panel2,12);bold(c,"← НАЗАД",35,y+30,11,text);}
        String formatBuild(int m){return String.format(Locale.getDefault(),"%02d:%02d",Math.max(0,m)/60,Math.max(0,m)%60);}
        void startUpgrade(int i){if(buildingRoom>=0){addLog("Сначала завершите текущее строительство.");return;}int cost=6+roomLevels[i]*4;if(mats<cost){addLog("Не хватает материалов: нужно "+cost+".");return;}mats-=cost;buildingRoom=i;buildRemaining=120+roomLevels[i]*90;addLog("Начато улучшение: "+rooms[i]+".");save();invalidate();}
        void repairRoom(int i){int cost=Math.max(1,(100-roomCondition[i])/15);if(roomCondition[i]>=95)return;if(mats>=cost){mats-=cost;roomCondition[i]=Math.min(100,roomCondition[i]+30);addLog(rooms[i]+": выполнен ремонт.");}save();}
        void processJobs(){int guards=0,medics=0;for(Survivor s:people)if(s.alive){s.fatigue=Math.max(0,Math.min(100,s.fatigue+(s.job.equals("Отдых")?-18:13)));if(s.job.equals("Еда"))food+=3+(s.role.equals("Сборщик")?s.skill:1)+roomLevels[1]/2;else if(s.job.equals("Вода"))water+=4;else if(s.job.equals("Материалы"))mats+=2+(s.role.equals("Механик")?2:0)+roomLevels[3]/2;else if(s.job.equals("Ремонт")){shelter=Math.min(100,shelter+3+s.skill);roomCondition[0]=Math.min(100,roomCondition[0]+2);}else if(s.job.equals("Охрана"))guards+=s.skill+roomLevels[4];else if(s.job.equals("Лечение"))medics+=s.skill+roomLevels[2];else{s.morale=Math.min(100,s.morale+4+roomLevels[5]/2);s.health=Math.min(100,s.health+2);}}threat=Math.max(0,threat-guards);if(medics>0)for(Survivor s:people)if(s.alive&&s.health<100)s.health=Math.min(100,s.health+medics/2);}
        void triggerEvent(){event=true;int e=rnd.nextInt(5);if(e==0)ev("ЧУЖАК У ДВЕРИ","Ночью в дверь стучит незнакомец.","ВПУСТИТЬ","ОТКАЗАТЬ");else if(e==1)ev("КОРОТКОЕ ЗАМЫКАНИЕ","В генераторной пахнет гарью. Оборудование перегрелось.","РЕМОНТ","ОТКЛЮЧИТЬ");else if(e==2)ev("БОЛЕЗНЬ","Одному из жителей нужна помощь.","ЛЕЧИТЬ","ОТДЫХ");else if(e==3)ev("МАРОДЁРЫ","У входа замечены вооружённые люди.","ОТДАТЬ ЕДУ","ОБОРОНА");else ev("ТИХАЯ НОЧЬ","Дом наконец затих. Можно восстановить силы.","ОТДЫХ","ДЕЖУРИТЬ");}
        void ev(String a,String b,String c,String d){eventTitle=a;eventText=b;eventChoices[0]=c;eventChoices[1]=d;}
        void choose(int n){if(eventTitle.equals("ЧУЖАК У ДВЕРИ")){if(n==0){people.add(make("Алекс","Выживший",2));food=Math.max(0,food-2);addLog("В дом принят Алекс.");}else addLog("Чужаку отказали.");}else if(eventTitle.equals("КОРОТКОЕ ЗАМЫКАНИЕ")){if(n==0&&mats>=3){mats-=3;roomCondition[0]=Math.min(100,roomCondition[0]+25);addLog("Генераторную отремонтировали.");}else{power=Math.max(0,power-8);roomCondition[0]=Math.max(10,roomCondition[0]-18);addLog("Генераторная повреждена.");}}else if(eventTitle.equals("БОЛЕЗНЬ")){Survivor q=people.get(rnd.nextInt(people.size()));q.health=Math.max(1,q.health+(n==0?10:-12));addLog(n==0?"Больному помогли.":"Болезнь ослабила жителя.");}else if(eventTitle.equals("МАРОДЁРЫ")){if(n==0)food=Math.max(0,food-7);else{threat=Math.max(0,threat-roomLevels[4]*3);roomCondition[4]=Math.max(10,roomCondition[4]-8);}addLog("Столкновение у баррикад завершилось.");}else{for(Survivor s:people)if(s.alive)s.fatigue=Math.max(0,s.fatigue-(n==0?15:5));addLog("Ночь использовали с пользой.");}event=false;save();invalidate();}
        void drawEvent(Canvas c){p.setColor(Color.argb(210,0,0,0));c.drawRect(0,0,W,H,p);float hh=H/scale,t=hh*.24f,b=hh*.73f;box(c,22,t,398,b,panel,18);txt(c,"СОБЫТИЕ",44,t+32,10,accent);bold(c,eventTitle,44,t+62,19,text);wrap(c,eventText,44,t+96,376,12,muted,18);for(int i=0;i<2;i++){float y=b-105+i*50;box(c,44,y,376,y+40,i==0?accent:panel2,10);bold(c,eventChoices[i],60,y+25,11,i==0?Color.rgb(30,27,23):text);}}
        void drawJobMenu(Canvas c){p.setColor(Color.argb(205,0,0,0));c.drawRect(0,0,W,H,p);float t=110;box(c,30,t,390,t+410,panel,16);bold(c,"НАЗНАЧИТЬ РАБОТУ",50,t+35,17,text);for(int i=0;i<jobs.length;i++){float y=t+55+i*45;box(c,48,y,372,y+36,panel2,8);bold(c,jobs[i],64,y+24,11,text);}}
        void drawGameOver(Canvas c){p.setColor(Color.argb(230,0,0,0));c.drawRect(0,0,W,H,p);float hh=H/scale;bold(c,"ПОСЛЕДНИЙ ДОМ ПАЛ",54,hh/2-60,22,text);txt(c,"Вы продержались "+day+" дней",110,hh/2-25,13,muted);box(c,55,hh/2+25,365,hh/2+82,accent,14);bold(c,"НАЧАТЬ ЗАНОВО",132,hh/2+60,13,Color.rgb(30,27,23));}
        void wrap(Canvas c,String s,float x,float y,float max,float size,int col,float step){p.setTextSize(sy(size));String[] ws=s.split(" ");String line="";float yy=y;for(String w:ws){if(p.measureText(line+w)>sy(max-x)){txt(c,line,x,yy,size,col);yy+=step;line="";}line+=w+" ";}txt(c,line,x,yy,size,col);}
        int roomAt(float x,float y,float top,boolean large){float bx=large?42:55,by=top+(large?38:28),bw=large?336:310,rh=large?136:82;if(x<bx||x>bx+bw||y<by||y>by+rh*3)return-1;int col=(int)((x-bx)/(bw/2)),row=(int)((y-by)/rh);int i=row*2+col;return i>=0&&i<6?i:-1;}
        @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX()/scale,y=e.getY()/scale,hh=H/scale;if(gameOver){if(y>hh/2)reset();return true;}if(event){float b=hh*.73f;if(y>=b-105&&y<=b-65)choose(0);else if(y>=b-55&&y<=b-15)choose(1);return true;}if(jobMenu){float t=110;for(int i=0;i<jobs.length;i++){float yy=t+55+i*45;if(y>=yy&&y<=yy+36){people.get(selected).job=jobs[i];jobMenu=false;addLog(people.get(selected).name+": "+jobs[i]+".");save();invalidate();return true;}}jobMenu=false;invalidate();return true;}if(screen==0){if(y>=hh-130&&y<=hh-72){screen=5;invalidate();return true;}int ri=roomAt(x,y,125,false);if(ri>=0){selectedRoom=ri;screen=4;invalidate();return true;}if(y>=462&&y<712){int i=(int)((y-462)/50);if(i>=0&&i<Math.min(5,people.size())){selected=i;screen=1;invalidate();return true;}}if(y>hh-78){int i=(int)((x-18)/96);if(i==1)screen=2;else if(i==2)screen=3;else if(i==3){if(paused){paused=false;speed=1;}else if(speed==1)speed=2;else if(speed==2)speed=4;else{paused=true;speed=1;}save();}invalidate();}}else if(screen==1){if(y>=390&&y<=455&&people.get(selected).alive){jobMenu=true;invalidate();}else if(y>hh-80){screen=0;invalidate();}}else if(screen==2){if(y>hh-80){screen=0;invalidate();}}else if(screen==3){int ri=roomAt(x,y,75,true);if(ri>=0){selectedRoom=ri;screen=4;invalidate();}else if(y>hh-80){screen=0;invalidate();}}else if(screen==4){if(y>=485&&y<=555)startUpgrade(selectedRoom);else if(y>=555&&y<=620){int idx=-1;for(int i=0;i<people.size();i++)if(people.get(i).alive){idx=i;break;}if(idx>=0){selected=idx;jobMenu=true;}}else if(y>hh-80){screen=3;invalidate();}}else if(screen==5){if(y>hh-80){screen=0;invalidate();}else{float top=68;float[][] pos={{90,top+78},{315,top+86},{92,top+245},{322,top+235},{132,top+370},{300,top+385}};for(int li=0;li<locations.size();li++){float dx=x-pos[li][0],dy=y-pos[li][1];if(dx*dx+dy*dy<1100){startExpedition(li);break;}}}}return true;}
    }
}
