package com.lastdom.game;

import android.app.Activity;
import android.os.Bundle;
import android.content.*;
import android.graphics.*;
import android.view.*;
import java.util.*;

public class MainActivity extends Activity {
    GameView view;
    @Override public void onCreate(Bundle b){ super.onCreate(b); getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN); view=new GameView(this); setContentView(view); }
    @Override protected void onPause(){ super.onPause(); view.save(); }

    static class Survivor {
        String name, role, job="Отдых"; int skill, health=100, hunger=10, fatigue=10, morale=75; boolean alive=true;
        Survivor(String n,String r,int s){name=n;role=r;skill=s;}
    }

    class GameView extends View {
        Paint p=new Paint(3), stroke=new Paint(3); Random rnd=new Random();
        ArrayList<Survivor> people=new ArrayList<>(); ArrayList<String> log=new ArrayList<>();
        String[] jobs={"Отдых","Еда","Вода","Материалы","Ремонт","Охрана","Лечение"};
        int day=1, food=28, water=34, power=24, mats=18, level=1, threat=12, shelter=100, selected=-1, screen=0;
        boolean event=false, gameOver=false, jobMenu=false; String eventTitle="",eventText=""; String[] eventChoices=new String[3]; int choiceCount=2;
        int W,H; float scale=1f; SharedPreferences sp;
        int bg=Color.rgb(14,16,20), panel=Color.rgb(28,31,37), panel2=Color.rgb(40,44,51), text=Color.rgb(238,234,224), muted=Color.rgb(166,166,160), accent=Color.rgb(213,143,70), danger=Color.rgb(190,72,65), good=Color.rgb(101,160,104), blue=Color.rgb(88,132,166);
        GameView(Context c){ super(c); p.setTypeface(Typeface.create("sans",Typeface.NORMAL)); stroke.setStyle(Paint.Style.STROKE); sp=getSharedPreferences("save_v02",0); load(); }
        Survivor make(String n,String r,int s){return new Survivor(n,r,s);}
        void defaults(){people.clear();people.add(make("Иван","Инженер",4));people.add(make("Мария","Врач",4));people.add(make("Сергей","Охрана",4));people.add(make("Анна","Сборщик",3));people.add(make("Павел","Механик",4));}
        void reset(){day=1;food=28;water=34;power=24;mats=18;level=1;threat=12;shelter=100;selected=-1;screen=0;event=false;gameOver=false;jobMenu=false;defaults();log.clear();addLog("Убежище готово. Пять человек начинают борьбу за жизнь.");save();invalidate();}
        void addLog(String s){log.add(0,"День "+day+": "+s);while(log.size()>30)log.remove(log.size()-1);}
        void save(){SharedPreferences.Editor e=sp.edit();e.putInt("day",day).putInt("food",food).putInt("water",water).putInt("power",power).putInt("mats",mats).putInt("level",level).putInt("threat",threat).putInt("shelter",shelter).putInt("count",people.size());for(int i=0;i<people.size();i++){Survivor s=people.get(i);String k="p"+i+"_";e.putString(k+"name",s.name).putString(k+"role",s.role).putString(k+"job",s.job).putInt(k+"skill",s.skill).putInt(k+"health",s.health).putInt(k+"hunger",s.hunger).putInt(k+"fatigue",s.fatigue).putInt(k+"morale",s.morale).putBoolean(k+"alive",s.alive);}e.putString("log",android.text.TextUtils.join("\n§\n",log));e.apply();}
        void load(){if(!sp.contains("day")){reset();return;}day=sp.getInt("day",1);food=sp.getInt("food",28);water=sp.getInt("water",34);power=sp.getInt("power",24);mats=sp.getInt("mats",18);level=sp.getInt("level",1);threat=sp.getInt("threat",12);shelter=sp.getInt("shelter",100);int n=sp.getInt("count",5);people.clear();for(int i=0;i<n;i++){String k="p"+i+"_";Survivor s=make(sp.getString(k+"name","Выживший"),sp.getString(k+"role","Житель"),sp.getInt(k+"skill",2));s.job=sp.getString(k+"job","Отдых");s.health=sp.getInt(k+"health",100);s.hunger=sp.getInt(k+"hunger",10);s.fatigue=sp.getInt(k+"fatigue",10);s.morale=sp.getInt(k+"morale",75);s.alive=sp.getBoolean(k+"alive",true);people.add(s);}String l=sp.getString("log","");if(!l.isEmpty())log.addAll(Arrays.asList(l.split("\\n§\\n")));}
        float sy(float y){return y*scale;} void txt(Canvas c,String s,float x,float y,float size,int col){p.setStyle(Paint.Style.FILL);p.setTextSize(sy(size));p.setColor(col);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));c.drawText(s,sy(x),sy(y),p);} void bold(Canvas c,String s,float x,float y,float size,int col){p.setStyle(Paint.Style.FILL);p.setTextSize(sy(size));p.setColor(col);p.setTypeface(Typeface.create("sans",Typeface.BOLD));c.drawText(s,sy(x),sy(y),p);} void box(Canvas c,float l,float t,float r,float b,int col,float rad){p.setColor(col);p.setStyle(Paint.Style.FILL);c.drawRoundRect(sy(l),sy(t),sy(r),sy(b),sy(rad),sy(rad),p);} void line(Canvas c,float a,float b,float d,float e,int col,float sw){stroke.setColor(col);stroke.setStrokeWidth(sy(sw));c.drawLine(sy(a),sy(b),sy(d),sy(e),stroke);}
        @Override protected void onDraw(Canvas c){super.onDraw(c);W=getWidth();H=getHeight();scale=W/420f;c.drawColor(bg);if(screen==0)drawMain(c);else if(screen==1)drawSurvivor(c);else if(screen==2)drawJournal(c);else drawRooms(c);if(event)drawEvent(c);if(jobMenu)drawJobMenu(c);if(gameOver)drawGameOver(c);}
        void drawHeader(Canvas c,String sub){bold(c,"ПОСЛЕДНИЙ ДОМ",20,32,21,text);txt(c,sub,20,53,12,muted);box(c,330,17,400,48,panel2,9);bold(c,"ДЕНЬ "+day,344,37,12,text);}
        void drawMain(Canvas c){drawHeader(c,"убежище • v0.2");drawResources(c);drawStatus(c);drawHouse(c);drawPeople(c);drawNav(c);}
        void drawResources(Canvas c){String[] a={"ЕДА "+food,"ВОДА "+water,"ЭН. "+power,"МАТ. "+mats};int[] co={accent,blue,Color.rgb(205,180,80),Color.rgb(145,126,105)};for(int i=0;i<4;i++){float x=20+i*96;box(c,x,68,x+88,108,panel,10);p.setColor(co[i]);c.drawCircle(sy(x+13),sy(88),sy(4),p);bold(c,a[i],x+22,93,11,text);}}
        void drawStatus(Canvas c){box(c,20,118,400,158,panel,10);txt(c,"ДОМ",32,136,10,muted);bar(c,32,143,112,7,shelter,good);txt(c,"УГРОЗА",155,136,10,muted);bar(c,155,143,235,7,threat,danger);txt(c,"УРОВЕНЬ "+level,278,146,12,accent);}
        void bar(Canvas c,float l,float t,float r,float h,int v,int col){box(c,l,t,r,t+h,Color.rgb(52,55,61),4);float rr=l+(r-l)*Math.max(0,Math.min(100,v))/100f;box(c,l,t,rr,t+h,col,4);}
        void drawHouse(Canvas c){float top=170;box(c,20,top,400,top+220,panel,16);p.setColor(Color.rgb(23,26,31));c.drawRect(sy(28),sy(top+8),sy(392),sy(top+212),p);float bl=120,br=300,bt=top+45,bb=top+190;p.setColor(Color.rgb(70,71,70));c.drawRect(sy(bl),sy(bt),sy(br),sy(bb),p);for(int row=0;row<3;row++)for(int col=0;col<3;col++){float x=bl+22+col*52,y=bt+20+row*40;p.setColor((row+col+day)%5==0?Color.rgb(91,63,43):Color.rgb(204,157,76));c.drawRect(sy(x),sy(y),sy(x+25),sy(y+25),p);}p.setColor(Color.rgb(42,42,41));c.drawRect(sy(194),sy(bb-42),sy(226),sy(bb),p);bold(c,"УБЕЖИЩЕ • "+aliveCount()+" ЖИВЫХ",34,top+205,11,muted);}
        int aliveCount(){int n=0;for(Survivor s:people)if(s.alive)n++;return n;}
        void drawPeople(Canvas c){float y=410;bold(c,"ЖИТЕЛИ",20,y,17,text);txt(c,"нажмите на карточку",240,y,11,muted);float cy=y+12;int max=Math.min(people.size(),5);for(int i=0;i<max;i++){Survivor s=people.get(i);float t=cy+i*61;box(c,20,t,400,t+54,s.alive?panel:Color.rgb(48,31,32),11);p.setColor(s.alive?accent:danger);c.drawCircle(sy(46),sy(t+27),sy(17),p);bold(c,s.name,72,t+20,14,text);txt(c,s.alive?s.role+" • "+s.job:"ПОГИБ",72,t+39,10,s.alive?muted:danger);txt(c,"❤"+s.health+"  ☺"+s.morale,300,t+22,10,s.alive?muted:danger);txt(c,"Г"+s.hunger+"  У"+s.fatigue,300,t+40,10,muted);}}
        void drawNav(Canvas c){float y=H/scale-70;box(c,16,y,404,y+54,panel,14);String[] n={"ДОМ","ЖУРНАЛ","КОМНАТЫ","ДЕНЬ +1"};for(int i=0;i<4;i++){float x=18+i*96; if(i==3)box(c,x+2,y+5,x+92,y+49,accent,10);bold(c,n[i],x+15,y+32,10,i==3?Color.rgb(30,27,23):(i==0?accent:text));}}
        void drawSurvivor(Canvas c){drawHeader(c,"карточка жителя");if(selected<0||selected>=people.size()){screen=0;return;}Survivor s=people.get(selected);box(c,20,72,400,182,panel,16);p.setColor(s.alive?accent:danger);c.drawCircle(sy(65),sy(123),sy(30),p);bold(c,s.name,112,106,24,text);txt(c,s.role+" • навык "+s.skill,112,132,13,muted);bold(c,s.alive?"ЖИВ":"ПОГИБ",112,157,12,s.alive?good:danger);String[] names={"ЗДОРОВЬЕ","ГОЛОД","УСТАЛОСТЬ","МОРАЛЬ"};int[] vals={s.health,s.hunger,s.fatigue,s.morale};int[] cols={good,danger,accent,blue};for(int i=0;i<4;i++){float y=215+i*58;txt(c,names[i],24,y,11,muted);bold(c,""+vals[i],350,y,12,text);bar(c,24,y+10,396,9,vals[i],cols[i]);}bold(c,"НАЗНАЧЕНИЕ",20,465,16,text);box(c,20,480,400,535,panel2,12);bold(c,s.job,38,514,15,accent);txt(c,"нажмите, чтобы изменить",190,513,11,muted);txt(c,"Профессия даёт бонус к подходящей работе.",20,570,12,muted);bottomBack(c);}
        void bottomBack(Canvas c){float y=H/scale-62;box(c,20,y,400,y+45,panel2,12);bold(c,"← НАЗАД",170,y+28,12,text);}
        void drawJournal(Canvas c){drawHeader(c,"журнал событий");bold(c,"ПОСЛЕДНИЕ СОБЫТИЯ",20,88,16,text);float y=110;for(int i=0;i<Math.min(9,log.size());i++){box(c,20,y,400,y+52,panel,10);wrap(c,log.get(i),32,y+20,382,11,i==0?text:muted,15);y+=60;}bottomBack(c);}
        void drawRooms(Canvas c){drawHeader(c,"комнаты и развитие");bold(c,"УБЕЖИЩЕ • УРОВЕНЬ "+level,20,88,17,text);String[] rooms={"Генераторная","Кухня","Медпункт","Мастерская","Баррикады"};String[] bonus={"электричество","меньше расход еды","лечение","больше материалов","защита от угроз"};for(int i=0;i<5;i++){float y=110+i*72;box(c,20,y,400,y+62,panel,11);bold(c,rooms[i],34,y+25,14,text);txt(c,bonus[i],34,y+45,10,muted);txt(c,"ур. "+Math.min(level,1+i/2+level/3),320,y+27,11,accent);}float y=485;box(c,20,y,400,y+55,accent,12);bold(c,"УЛУЧШИТЬ ДОМ • 10 МАТ. + 5 ЭН.",52,y+34,12,Color.rgb(30,27,23));bottomBack(c);}
        void drawJobMenu(Canvas c){p.setColor(Color.argb(190,0,0,0));c.drawRect(0,0,W,H,p);float l=32,r=388,t=130;box(c,l,t,r,t+390,panel,18);bold(c,"ВЫБЕРИТЕ РАБОТУ",52,t+38,18,text);for(int i=0;i<jobs.length;i++){float y=t+58+i*43;box(c,48,y,372,y+35,panel2,8);bold(c,jobs[i],64,y+23,12,i==0?muted:text);}txt(c,"Работа применяется со следующего дня",52,t+375,10,muted);}
        void wrap(Canvas c,String s,float x,float y,float max,float size,int col,float step){p.setTextSize(sy(size));String[] words=s.split(" ");String line="";float yy=y;for(String w:words){if(p.measureText(line+w)>sy(max-x)){txt(c,line,x,yy,size,col);yy+=step;line="";}line+=w+" ";}txt(c,line,x,yy,size,col);}
        void drawEvent(Canvas c){p.setColor(Color.argb(205,0,0,0));c.drawRect(0,0,W,H,p);float l=22,r=398,t=H/scale*.20f,b=H/scale*.78f;box(c,l,t,r,b,panel,20);txt(c,"СОБЫТИЕ",l+22,t+31,10,accent);bold(c,eventTitle,l+22,t+62,21,text);wrap(c,eventText,l+22,t+94,r-22,13,muted,19);for(int i=0;i<choiceCount;i++){float y=b-55-(choiceCount-1-i)*48;box(c,l+22,y,r-22,y+39,i==0?accent:panel2,10);bold(c,eventChoices[i],l+38,y+25,11,i==0?Color.rgb(28,25,22):text);}}
        void drawGameOver(Canvas c){p.setColor(Color.argb(230,0,0,0));c.drawRect(0,0,W,H,p);bold(c,"ПОСЛЕДНИЙ ДОМ ПАЛ",54,H/scale/2-70,24,text);txt(c,"Вы продержались "+day+" дней",115,H/scale/2-35,14,muted);txt(c,"Уровень убежища: "+level,125,H/scale/2-10,12,muted);box(c,55,H/scale/2+30,365,H/scale/2+86,accent,14);bold(c,"НАЧАТЬ ЗАНОВО",132,H/scale/2+65,13,Color.rgb(30,27,23));}
        void processJobs(){int guards=0,medics=0;for(Survivor s:people){if(!s.alive)continue;s.hunger=Math.min(100,s.hunger+12);s.fatigue=Math.min(100,s.fatigue+(s.job.equals("Отдых")?-18:13));if(s.job.equals("Еда"))food+=3+(s.role.equals("Сборщик")?s.skill:1);else if(s.job.equals("Вода"))water+=4+(s.role.equals("Сборщик")?2:0);else if(s.job.equals("Материалы"))mats+=2+(s.role.equals("Механик")?s.skill/2:0);else if(s.job.equals("Ремонт")){int q=3+(s.role.equals("Инженер")||s.role.equals("Механик")?s.skill:1);shelter=Math.min(100,shelter+q);mats=Math.max(0,mats-1);}else if(s.job.equals("Охрана"))guards+=s.skill+(s.role.equals("Охрана")?3:0);else if(s.job.equals("Лечение"))medics+=s.skill+(s.role.equals("Врач")?4:0);else {s.morale=Math.min(100,s.morale+4);s.health=Math.min(100,s.health+2);}}
            threat=Math.max(0,threat-guards);if(medics>0)for(Survivor s:people)if(s.alive&&s.health<100)s.health=Math.min(100,s.health+medics/2);
        }
        void nextDay(){if(gameOver||event)return;int alive=aliveCount();if(alive==0){gameOver=true;invalidate();return;}processJobs();food-=alive;water-=alive*2;power-=Math.max(1,level);threat=Math.min(100,threat+3+rnd.nextInt(5));for(Survivor s:people){if(!s.alive)continue;if(food<0||water<0){s.health-=8;s.morale-=6;}if(s.hunger>80)s.health-=7;if(s.fatigue>85)s.health-=5;if(threat>75)s.morale-=4;s.health=Math.max(0,s.health);s.morale=Math.max(0,s.morale);if(s.health<=0){s.alive=false;addLog(s.name+" погиб.");}}food=Math.max(0,food);water=Math.max(0,water);power=Math.max(0,power);if(power==0)shelter=Math.max(0,shelter-5);if(threat>70)shelter=Math.max(0,shelter-rnd.nextInt(5));day++;if(aliveCount()==0||shelter<=0){gameOver=true;save();invalidate();return;}if(rnd.nextInt(100)<78)triggerEvent();else addLog("Ночь прошла спокойно.");save();invalidate();}
        void triggerEvent(){int e=rnd.nextInt(10);event=true;choiceCount=2;if(e==0){ev("ЧУЖАК У ДВЕРИ","Ночью в дверь стучит незнакомец. Он просит укрытия.","ВПУСТИТЬ","ОТКАЗАТЬ");}else if(e==1){ev("СТАРЫЙ СКЛАД","В соседнем доме найден склад. Поход опасен, но запасы пригодятся.","ОБЫСКАТЬ","НЕ РИСКОВАТЬ");}else if(e==2){ev("БОЛЕЗНЬ","У одного из жителей высокая температура. Мария предлагает заняться лечением.","ЛЕЧИТЬ","ПУСТЬ ОТДЫХАЕТ");}else if(e==3){ev("МАРОДЁРЫ","Вооружённые люди требуют еду и воду. Уровень угрозы растёт.","ОТДАТЬ ЗАПАСЫ","ДАТЬ ОТПОР");}else if(e==4){ev("СИЛЬНЫЙ ДОЖДЬ","Можно организовать сбор дождевой воды, потратив немного материалов.","СОБРАТЬ ВОДУ","ПРОПУСТИТЬ");}else if(e==5){ev("ПОЖАР","Проводка на втором этаже загорелась. Нужно действовать немедленно.","ТУШИТЬ","ИЗОЛИРОВАТЬ ЭТАЖ");}else if(e==6){ev("СПОР В УБЕЖИЩЕ","Жители спорят из-за распределения еды. Напряжение растёт.","РАЗОБРАТЬСЯ","НЕ ВМЕШИВАТЬСЯ");}else if(e==7){ev("РАДИОСИГНАЛ","Старый приёмник поймал короткое сообщение: «Есть безопасное место...»", "ОТВЕТИТЬ","МОЛЧАТЬ");}else if(e==8){ev("НАХОДКА ПАВЛА","Павел нашёл детали для генератора. Их можно использовать сейчас или разобрать.","ПОЧИНИТЬ","РАЗОБРАТЬ");}else{ev("ТИХАЯ НОЧЬ","Редкая спокойная ночь. Люди наконец могут немного прийти в себя.","ОТДОХНУТЬ","ДЕЖУРИТЬ");}}
        void ev(String a,String b,String c,String d){eventTitle=a;eventText=b;eventChoices[0]=c;eventChoices[1]=d;}
        void choose(int n){if(!event)return;if(eventTitle.equals("ЧУЖАК У ДВЕРИ")){if(n==0){Survivor z=make("Алекс","Выживший",2);z.morale=60;people.add(z);food=Math.max(0,food-2);addLog("Принят новый житель — Алекс.");}else addLog("Незнакомцу отказали.");}else if(eventTitle.equals("СТАРЫЙ СКЛАД")){if(n==0){if(rnd.nextInt(100)<70){mats+=8;food+=6;addLog("Со склада принесли ценные запасы.");}else{hurtRandom(18);addLog("Поход на склад закончился травмой.");}}else addLog("Решили не рисковать.");}else if(eventTitle.equals("БОЛЕЗНЬ")){if(n==0){water=Math.max(0,water-3);healRandom(20);addLog("Больному оказали помощь.");}else{hurtRandom(12);addLog("Болезнь ослабила одного из жителей.");}}else if(eventTitle.equals("МАРОДЁРЫ")){if(n==0){food=Math.max(0,food-7);water=Math.max(0,water-8);threat=Math.max(0,threat-8);addLog("Часть запасов отдали мародёрам.");}else{int guards=0;for(Survivor s:people)if(s.alive&&s.job.equals("Охрана"))guards+=s.skill;if(guards+rnd.nextInt(8)>=7){threat=Math.max(0,threat-15);addLog("Оборона выдержала нападение.");}else{hurtRandom(30);shelter-=12;addLog("Мародёры прорвали часть обороны.");}}}else if(eventTitle.equals("СИЛЬНЫЙ ДОЖДЬ")){if(n==0&&mats>=2){mats-=2;water+=16;addLog("Собрали дождевую воду.");}else addLog("Дождь не использовали.");}else if(eventTitle.equals("ПОЖАР")){if(n==0){water=Math.max(0,water-8);shelter-=4;addLog("Пожар потушен.");}else{shelter-=15;addLog("Этаж изолирован, дом повреждён.");}}else if(eventTitle.equals("СПОР В УБЕЖИЩЕ")){for(Survivor s:people)if(s.alive)s.morale=Math.max(0,s.morale+(n==0?5:-7));addLog(n==0?"Конфликт удалось погасить.":"Ссора ударила по морали.");}else if(eventTitle.equals("РАДИОСИГНАЛ")){if(n==0){threat+=8;addLog("Вы ответили на неизвестный радиосигнал.");}else addLog("Решили сохранить радиомолчание.");}else if(eventTitle.equals("НАХОДКА ПАВЛА")){if(n==0){power+=12;addLog("Генератор получил запас энергии.");}else{mats+=6;addLog("Детали разобрали на материалы.");}}else{for(Survivor s:people)if(s.alive){s.fatigue=Math.max(0,s.fatigue-(n==0?15:5));s.morale=Math.min(100,s.morale+(n==0?6:1));}if(n==1)threat=Math.max(0,threat-5);addLog("Ночь использовали с пользой.");}shelter=Math.max(0,shelter);threat=Math.min(100,Math.max(0,threat));event=false;save();invalidate();}
        void hurtRandom(int d){ArrayList<Survivor>a=new ArrayList<>();for(Survivor s:people)if(s.alive)a.add(s);if(!a.isEmpty()){Survivor s=a.get(rnd.nextInt(a.size()));s.health=Math.max(1,s.health-d);}}void healRandom(int d){Survivor best=null;for(Survivor s:people)if(s.alive&&(best==null||s.health<best.health))best=s;if(best!=null)best.health=Math.min(100,best.health+d);}
        void upgrade(){if(event||gameOver)return;if(mats>=10&&power>=5){mats-=10;power-=5;level++;shelter=Math.min(100,shelter+12);addLog("Дом улучшен до уровня "+level+".");}else addLog("Не хватает ресурсов для улучшения.");save();invalidate();}
        @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX()/scale,y=e.getY()/scale,hh=H/scale;if(gameOver){if(y>hh/2+15){reset();}return true;}if(event){float b=hh*.78f;for(int i=0;i<choiceCount;i++){float yy=b-55-(choiceCount-1-i)*48;if(y>=yy&&y<=yy+42){choose(i);break;}}return true;}if(jobMenu){float t=130;for(int i=0;i<jobs.length;i++){float yy=t+58+i*43;if(y>=yy&&y<=yy+35){people.get(selected).job=jobs[i];jobMenu=false;addLog(people.get(selected).name+": назначение — "+jobs[i]+".");save();invalidate();return true;}}jobMenu=false;invalidate();return true;}if(screen==0){if(y>=422&&y<422+5*61){int i=(int)((y-422)/61);if(i>=0&&i<Math.min(5,people.size())){selected=i;screen=1;invalidate();return true;}}if(y>hh-80){int i=(int)((x-18)/96);if(i==1)screen=2;else if(i==2)screen=3;else if(i==3)nextDay();invalidate();}}else if(screen==1){if(y>=480&&y<=540&&people.get(selected).alive){jobMenu=true;invalidate();}else if(y>hh-80){screen=0;invalidate();}}else if(screen==2){if(y>hh-80){screen=0;invalidate();}}else if(screen==3){if(y>=480&&y<=550)upgrade();else if(y>hh-80){screen=0;invalidate();}}return true;}
    }
}
