#!/usr/bin/env python3
"""ONLINE 0.4 actual controllers, combined atomic saves, legacy migration and Canvas/input.
Android doubles and injected clocks do not establish physical device rendering or FPS.
"""
import sys
sys.dont_write_bytecode=True
from pathlib import Path
import tempfile
import online_combat_regression as combat
import refactor_regression as fixtures

PROBE=combat.PROBE[:combat.PROBE.index(' public static void main(')]+r'''
 static MockOnlineWorldRepository allianceRepo(MemoryPreferences disk){MockOnlineWorldRepository r=persistent(disk);require(r.createAlliance("Северный союз").success,"create named demo alliance");require(r.invite("demo_ember").success&&r.invite("demo_beacon").success,"invite two fictional shelters");for(int i=0;i<10;i++)r.advanceMinute();return r;}
 static String firstEvent(MockOnlineWorldRepository r,boolean debug){if(debug)require(r.createDemoEvent().success,"safe debug event creation");else for(int i=0;i<15;i++)r.advanceMinute();return r.gameplay().civic.events.get(0).id;}
 static long operationSeed(MockOnlineWorldRepository r,String event,List<String> ids,List<String> allies,boolean success){OnlineCombatSquad own=new OnlineCombatSquad(ids.stream().map(id->r.gameplay().combat.fighter(id)).collect(java.util.stream.Collectors.toList()));OnlineCombatSquad team=OnlineCityEventController.allies(r.load(),allies);return coopSeed(r.gameplay().civic.event(event).type.zoneId,own,team,success);}
 static void alliances(){
  MemoryPreferences disk=new MemoryPreferences();MockOnlineWorldRepository r=persistent(disk);String old=ledger(r);require(old.startsWith("1|")&&!r.gameplay().civic.used,"old save remains v1 until new sections used");require(!r.createAlliance(" ").success&&!r.createAlliance("bad|name").success&&old.equals(ledger(r)),"invalid names cannot partially create alliance");
  require(r.activateCivic().success&&ledger(r).startsWith("3|"),"activate version 3 without creating members/events");require(r.createAlliance("  Радиосеть 4  ").success&&r.gameplay().civic.alliance.name.equals("Радиосеть 4"),"trim and persist user name");String created=ledger(r);require(!r.createAlliance("Дубликат").success&&created.equals(ledger(r)),"only one alliance");
  for(String id:Arrays.asList("demo_ember","demo_beacon","demo_foundry","demo_outpost")){require(r.invite(id).success,"pending invitation "+id);String invitation=ledger(r);require(!r.invite(id).success&&invitation.equals(ledger(r)),"duplicate invite blocked "+id);}
  require(r.gameplay().civic.alliance.members.size()==5&&r.gameplay().civic.alliance.reputation()==0,"no duplicated member or invitation reward");
  for(int i=0;i<9;i++)r.advanceMinute();require(r.gameplay().civic.alliance.member("demo_ember").invitation==OnlineAllianceMember.Invitation.PENDING,"answer waits for game minutes");r=persistent(disk);r.advanceMinute();require(r.gameplay().civic.alliance.member("demo_ember").invitation==OnlineAllianceMember.Invitation.ACCEPTED&&r.gameplay().civic.alliance.member("demo_beacon").invitation==OnlineAllianceMember.Invitation.ACCEPTED,"clear low-threshold invitations accepted");require(r.gameplay().civic.alliance.member("demo_foundry").invitation==OnlineAllianceMember.Invitation.REJECTED&&r.gameplay().civic.alliance.member("demo_outpost").invitation==OnlineAllianceMember.Invitation.REJECTED,"unmet reputation thresholds rejected");
  String resolved=ledger(r);require(!r.invite("demo_foundry").success&&resolved.equals(ledger(r)),"rejection cannot be retried before conditions change");require(resolved.equals(ledger(persistent(disk))),"answers/name/member totals restore exactly");
 }
 static void schedule(){
  MockOnlineWorldRepository r=new MockOnlineWorldRepository();for(int i=0;i<200;i++)r.advanceMinute();require(!r.gameplay().civic.used&&r.gameplay().civic.events.isEmpty()&&r.gameplay().civic.minute==0,"old mechanics never silently activate new schedule");r.activateCivic();for(int i=0;i<14;i++)r.advanceMinute();require(r.gameplay().civic.events.isEmpty(),"first spawn not early");r.advanceMinute();require(r.gameplay().civic.events.size()==1&&r.gameplay().civic.event("city_event_1").appearedMinute==15,"scheduled first spawn");String same=ledger(r);for(int i=0;i<30;i++){r.load();r.gameplay();r.activateCivic();}require(same.equals(ledger(r))&&r.gameplay().civic.events.size()==1,"reopening sections does not duplicate schedule");
  require(r.createDemoEvent().success,"explicit debug spawn");String spawned=ledger(r);require(!r.createDemoEvent().success&&spawned.equals(ledger(r)),"debug cooldown blocks unlimited identical events");for(int i=0;i<120;i++)r.advanceMinute();require(r.gameplay().civic.events.size()==3,"scheduled interval plus one manual event only");
  for(int i=0;i<120;i++)r.advanceMinute();require(r.gameplay().civic.event("city_event_1").state==OnlineCityEvent.State.EXPIRED,"available event expires after 240 minutes");
  Set<String> ids=new HashSet<>();Set<OnlineCityEvent.Type> types=new HashSet<>();for(int i=0;i<700;i++)r.advanceMinute();for(OnlineCityEvent e:r.gameplay().civic.events){require(ids.add(e.id)&&e.expiresMinute-e.appearedMinute==240&&OnlineCombatRules.coopMinutes(e.type.zoneId)>0,"unique persistent IDs/lifetime/existing zones");types.add(e.type);}require(types.size()==5,"all five configured event types appear");
 }
 static void operations(){
  for(int type=0;type<5;type++)for(boolean success:new boolean[]{false,true})for(int size=1;size<=3;size++)for(int allyCount=1;allyCount<=2;allyCount++){
   MemoryPreferences disk=new MemoryPreferences();MockOnlineWorldRepository r=allianceRepo(disk);String event=firstEvent(r,true);if(type>0){long spawn=15+(type-1)*120;while(r.gameplay().civic.minute<spawn)r.advanceMinute();event="city_event_"+(type+1);}require(r.gameplay().civic.event(event).type.ordinal()==type,"each configured event launches its real operation");String id=r.gameplay().combat.requestId();List<String> ids=fighters(size==1?new int[]{1}:size==2?new int[]{1,2}:new int[]{1,2,3}),allies=allyCount==1?Arrays.asList("demo_ember"):Arrays.asList("demo_ember","demo_beacon");long seed=operationSeed(r,event,ids,allies,success);String before=ledger(r);
   require(!r.startOperation(id,event,ids,allies,seed,false).success&&before.equals(ledger(r)),"explicit confirmation required");require(!r.startOperation(id,event,ids,Arrays.asList("demo_foundry"),seed,true).success&&before.equals(ledger(r)),"unaccepted ally rejected atomically");require(r.startOperation(id,event,ids,allies,seed,true).success,"send configured alliance operation");OnlineCoopExpedition trip=r.gameplay().combat.expedition(id);require(trip.success==success&&r.gameplay().civic.event(event).state==OnlineCityEvent.State.ACTIVE&&r.gameplay().civic.operation(id).state==OnlineCoopOperation.State.ACTIVE,"existing PvE trip and event become active together");
   String sent=ledger(r);require(!r.startOperation(id,event,ids,allies,seed+1,true).success&&sent.equals(ledger(r)),"same job/event cannot reroll");require(!r.startPvp(r.gameplay().combat.requestId(),"pvp_frontier",fighters(1),OnlineCombatRules.Tactic.BALANCED,1,true).success&&!r.recover("radio_1").success,"operation member excluded from PvP and recovery");require(!r.startCoop(r.gameplay().combat.requestId(),"pve_industry",allies.get(0),fighters(6),1,true).success,"virtual operation ally excluded from old cooperative tasks");
   OnlineInventory inventory=r.gameplay().inventory;for(int i=0;i<trip.durationMinutes-1;i++)r.advanceMinute();require(r.gameplay().civic.alliance.reputation()==0&&!r.gameplay().civic.operation(id).report.applied,"no early reputation/contribution/reward");for(OnlineInventory.Resource res:OnlineInventory.Resource.values())require(r.gameplay().inventory.amount(res)==inventory.amount(res),"no early inventory award");String active=ledger(r);r=persistent(disk);require(active.equals(ledger(r)),"active job/event/clock/reports restore without RNG");r.advanceMinute();
   OnlineCoopOperation op=r.gameplay().civic.operation(id);require(op.state==OnlineCoopOperation.State.COMPLETED&&op.report.applied&&r.gameplay().civic.event(event).state==OnlineCityEvent.State.COMPLETED,"all completion flags committed together");for(OnlineInventory.Resource res:OnlineInventory.Resource.values())require(r.gameplay().inventory.amount(res)==inventory.amount(res)+trip.loot.amount(res),"existing PvE grant applied once");OnlineAlliance a=r.gameplay().civic.alliance;require(a.reputation()==(success?10+5*allyCount:0)&&a.successes()==(success?1:0),"success-only alliance totals");int shares=0;for(Map.Entry<String,Integer> share:op.report.shares.entrySet()){shares+=share.getValue();OnlineAllianceMember m=a.member(share.getKey());require(m.contribution==(success?share.getValue():0)&&m.successes==(success?1:0),"exact saved member contribution");}require(shares==100,"contribution percentages sum to 100");
   r=persistent(disk);int rep=r.gameplay().civic.alliance.reputation();OnlineInventory awarded=r.gameplay().inventory;for(int i=0;i<30;i++){r.advanceMinute();r.advanceSecond();r.gameplay().civic.operation(id);}require(r.gameplay().civic.alliance.reputation()==rep&&r.gameplay().civic.alliance.successes()==(success?1:0),"ticks/report/restart do not re-credit alliance");for(OnlineInventory.Resource res:OnlineInventory.Resource.values())require(r.gameplay().inventory.amount(res)==awarded.amount(res),"no duplicate old expedition award");
   if(success){require(r.invite("demo_foundry").success,"success unlocks threshold invitation");for(int i=0;i<10;i++)r.advanceMinute();require(r.gameplay().civic.alliance.member("demo_foundry").invitation==OnlineAllianceMember.Invitation.ACCEPTED,"higher reputation has actual acceptance effect");}
  }
  MockOnlineWorldRepository r=allianceRepo(new MemoryPreferences());String event=firstEvent(r,true);String id=r.gameplay().combat.requestId();List<String> ids=fighters(1,2,3);int one=OnlineCombatRules.coopChance("pve_infected",squad(r.gameplay().combat,1,2,3),OnlineCityEventController.allies(r.load(),Arrays.asList("demo_ember"))),two=OnlineCombatRules.coopChance("pve_infected",squad(r.gameplay().combat,1,2,3),OnlineCityEventController.allies(r.load(),Arrays.asList("demo_ember","demo_beacon")));require(two>one,"second ally increases actual operation success chance");long seed=0;while(true){int roll=new Random(seed).nextInt(100);if(roll>=one&&roll<two)break;seed++;}require(r.startOperation(id,event,ids,Arrays.asList("demo_ember","demo_beacon"),seed,true).success&&r.gameplay().combat.expedition(id).success,"ally contribution changes same-seed outcome");
 }

 static void lifecycleEdges(){
  MemoryPreferences disk=new MemoryPreferences();MockOnlineWorldRepository r=allianceRepo(disk);String event=firstEvent(r,true);long expiry=r.gameplay().civic.event(event).expiresMinute;while(r.gameplay().civic.minute<expiry-1)r.advanceMinute();long seed=operationSeed(r,event,fighters(1),Arrays.asList("demo_ember"),true);require(r.startOperation("online_job_1",event,fighters(1),Arrays.asList("demo_ember"),seed,true).success,"last available minute still accepts an operation");r.advanceMinute();require(r.gameplay().civic.event(event).state==OnlineCityEvent.State.ACTIVE,"accepted operation survives event deadline");r=persistent(disk);for(int i=1;i<150;i++)r.advanceMinute();require(r.gameplay().civic.event(event).state==OnlineCityEvent.State.COMPLETED&&r.gameplay().civic.alliance.reputation()==15,"operation completes once after event deadline and restart");
  OnlineWorldGameplay.Data d=r.gameplay();OnlineAllianceMember owner=d.civic.alliance.member(OnlineAllianceMember.PLAYER);List<OnlineAllianceMember> members=new ArrayList<>(d.civic.alliance.members);members.set(0,new OnlineAllianceMember(owner.shelterId,owner.invitationId,owner.invitation,owner.resolveMinute,owner.willAccept,owner.reputation+1,owner.contribution,owner.successes));OnlineCivicState bad=new OnlineCivicState(true,d.civic.minute,d.civic.nextSpawn,d.civic.lastDebug,d.civic.nextEvent,new OnlineAlliance(d.civic.alliance.name,members),d.civic.events,d.civic.operations);try{OnlineDemoSaveStore.encode(d.withCivic(bad));throw new AssertionError("unmatched reputation accepted");}catch(IllegalArgumentException expected){checks++;}
  r=allianceRepo(new MemoryPreferences());event=firstEvent(r,true);require(r.startPvp("online_job_1","pvp_frontier",fighters(1),OnlineCombatRules.Tactic.BALANCED,1,true).success,"existing PvP starts alongside alliance");String before=ledger(r);require(!r.startOperation("online_job_2",event,fighters(1),Arrays.asList("demo_ember"),1,true).success&&before.equals(ledger(r)),"existing PvP fighter cannot join an alliance operation");
  require(r.startCoop("online_job_2","pve_industry","demo_ember",fighters(2),1,true).success,"old cooperative job remains accessible");before=ledger(r);require(!r.startOperation("online_job_3",event,fighters(3),Arrays.asList("demo_ember"),1,true).success&&before.equals(ledger(r)),"old cooperative ally cannot be double assigned to a city event");
 }
 static void persistenceAndFailure(){
  for(boolean afterCommit:new boolean[]{false,true}){
   FailingPreferences disk=new FailingPreferences();MockOnlineWorldRepository r=allianceRepo(disk);String event=firstEvent(r,true);long seed=operationSeed(r,event,fighters(1),Arrays.asList("demo_ember"),true);r.startOperation("online_job_1",event,fighters(1),Arrays.asList("demo_ember"),seed,true);OnlineCoopExpedition trip=r.gameplay().combat.expedition("online_job_1");for(int i=0;i<trip.durationMinutes-1;i++)r.advanceMinute();String before=ledger(r);disk.fail=true;disk.applyThenFail=afterCommit;require(!r.advanceMinute()&&!r.writable()&&before.equals(ledger(r)),"I/O failure does not publish partial completion");disk.fail=disk.applyThenFail=false;MockOnlineWorldRepository loaded=persistent(disk);require(loaded.writable(),"whole old/new save restored after failure");if(!afterCommit)loaded.advanceMinute();require(loaded.gameplay().civic.alliance.reputation()==15&&loaded.gameplay().civic.operation("online_job_1").report.applied,"one successful completion after either failure boundary");String saved=ledger(loaded);require(saved.equals(ledger(persistent(disk))),"applied flag and reports survive failure/restart");
  }
  MemoryPreferences disk=new MemoryPreferences();MockOnlineWorldRepository old=persistent(disk);old.execute("ember_water",OnlineWorldGameplay.Kind.TRADE);old.startPvp("online_job_1","pvp_frontier",fighters(1),OnlineCombatRules.Tactic.BALANCED,42,true);String v2=ledger(old);require(v2.startsWith("2|"),"legacy ONLINE 0.3 v2 fixture");old=persistent(disk);old.activateCivic();require(ledger(old).startsWith("3|")&&old.gameplay().operations.size()==1&&old.gameplay().combat.battles.size()==1,"v2 migration keeps trade and battle snapshots");old.createAlliance("Демо-союз");for(int i=0;i<30;i++)old.advanceSecond();require(old.gameplay().civic.alliance!=null&&old.gameplay().combat.battle("online_job_1").effectsApplied,"old combat/delivery preserve civic state");old.execute("ember_help",OnlineWorldGameplay.Kind.HELP);old.preparePvp("pvp_frontier",true);old.disablePvp();old.recover("radio_1");require(ledger(old).equals(ledger(persistent(disk))),"all old commands keep version3 membership/history/clock");
  String valid=ledger(old);disk.values.put(OnlineDemoSaveStore.KEY,valid.substring(0,valid.length()-1)+"x");MockOnlineWorldRepository broken=persistent(disk);require(!broken.writable()&&!broken.createDemoEvent().success&&!broken.createAlliance("Подмена").success,"corrupt state fails closed without reward reset");
 }
 static void civicRow(GameView v,OnlineCivicPanelController.Action action,String id){OnlineCivicPanelController p=v.onlineWorld.civicPanel;List<OnlineCivicPanelController.Row> rows=p.rows();int index=-1;for(int i=0;i<rows.size();i++)if(rows.get(i).action==action&&(id.isEmpty()||rows.get(i).id.equals(id))){index=i;break;}require(index>=0,"civic row exists "+action+" "+id);p.scroll=Math.min(Math.max(0,rows.size()*64-(int)(geometry(v).height-148-112)),index*64);tap(v,60,112+index*64-p.scroll+22);draw(v);}
 static void civicUi(){
  for(int width:new int[]{420,840})for(int height:new int[]{360,500,640,840,1200}){
   GameView v=interactive(width,height);radio(v);v.game.paused=true;String solo=snapshot(v);OnlineWorldGeometry g=geometry(v);tap(v,205,84);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.ALLIANCE,"48-unit alliance tab opens section");text(draw(v),"СОЮЗЫ");require(v.onlineWorld.state.gameplay.civic.events.isEmpty(),"opening alliance does not spawn events");civicRow(v,OnlineCivicPanelController.Action.NAME,"");require(v.onlineWorld.state.panel==OnlineWorldState.Panel.ALLIANCE_NAME,"editable custom name screen");civicRow(v,OnlineCivicPanelController.Action.DELETE,"clear");civicRow(v,OnlineCivicPanelController.Action.KEYS,"");civicRow(v,OnlineCivicPanelController.Action.KEYS,"");require(v.onlineWorld.civicPanel.name.equals("АА"),"Canvas keyboard accepts player-specified alliance name");tap(v,180,height-114);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.ALLIANCE,"save entered name returns to alliance");tap(v,180,height-114);require(v.onlineWorld.state.gameplay.civic.alliance.name.equals("АА"),"create persists entered name");
   civicRow(v,OnlineCivicPanelController.Action.INVITE,"demo_ember");civicRow(v,OnlineCivicPanelController.Action.INVITE,"demo_beacon");for(int i=0;i<10;i++)v.onlineWorld.advanceMinute();tap(v,335,84);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.EVENTS,"events tab opens dedicated scrollable list");tap(v,180,height-114);String event=v.onlineWorld.state.gameplay.civic.events.get(0).id;int count=v.onlineWorld.state.gameplay.civic.events.size();tap(v,80,84);tap(v,335,84);require(v.onlineWorld.state.gameplay.civic.events.size()==count,"map/events switching creates no duplicate");civicRow(v,OnlineCivicPanelController.Action.EVENT,event);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.CITY_EVENT,"event details opened");text(draw(v),"СОВМЕСТНАЯ ОПЕРАЦИЯ");tap(v,180,height-114);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.OPERATION_PREP,"large operation action opens preparation");
   civicRow(v,OnlineCivicPanelController.Action.FIGHTER,"radio_1");civicRow(v,OnlineCivicPanelController.Action.ALLY,"demo_ember");civicRow(v,OnlineCivicPanelController.Action.ALLY,"demo_beacon");tap(v,180,height-114);require(v.onlineWorld.civicPanel.confirming,"separate dispatch confirmation");text(draw(v),"ОТПРАВИТЬ ОПЕРАЦИЮ");tap(v,180,height-114);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.OPERATION_REPORT,"dispatch shows active saved operation report");String id=v.onlineWorld.civicPanel.reportId;require(v.onlineWorld.civicPanel.routes.containsKey(id),"active mission has animated road route");tap(v,80,84);for(int i=0;i<6;i++)v.onlineWorld.advanceMinute();for(int i=0;i<60;i++)frame(v,16_666_667);require(v.onlineWorld.civicPanel.routes.get(id).progress>0,"visual marker smoothly follows saved progress");
   MemoryPreferences disk=Context.namedPreferences.get(OnlineDemoSaveStore.FILE);String saved=OnlineDemoSaveStore.encode(v.onlineWorld.state.gameplay);GameView loaded=new GameView(new Context());loaded.game.rnd=new Quiet();radio(loaded);require(saved.equals(OnlineDemoSaveStore.encode(loaded.onlineWorld.state.gameplay))&&loaded.onlineWorld.civicPanel.routes.containsKey(id),"active event/operation/route restores");for(int i=6;i<150;i++)loaded.onlineWorld.advanceMinute();require(!loaded.onlineWorld.civicPanel.routes.containsKey(id),"completed route disappears");loaded.onlineWorld.civicPanel.showOperation(id);require(loaded.onlineWorld.civicPanel.rows().stream().anyMatch(row->row.title.startsWith("Наград")),"completed report explains reward or failure");draw(loaded);loaded.onlineWorld.combatPanel.showReport(id);require(loaded.onlineWorld.state.panel==OnlineWorldState.Panel.OPERATION_REPORT,"old PvE history redirects to alliance report");
   require(solo.equals(snapshot(loaded)),"alliance/events/operations/map animations preserve complete save_v02 state");String report=OnlineDemoSaveStore.encode(loaded.onlineWorld.state.gameplay);GameView completed=new GameView(new Context());radio(completed);require(!completed.onlineWorld.civicPanel.routes.containsKey(id)&&report.equals(OnlineDemoSaveStore.encode(completed.onlineWorld.state.gameplay)),"restart cannot resurrect completed route or effects");tap(completed,205,84);tap(completed,350,35);require(completed.onlineWorld.state.panel==OnlineWorldState.Panel.INVENTORY,"inventory header remains accessible from alliance section");completed.onlineWorld.closeCard();tap(completed,335,84);tap(completed,58,35);require(completed.game.screen==GameView.CITY_MAP&&solo.equals(snapshot(completed)),"back header exits event section without affecting solo save");
  }
 }
 static void gameClockAndRoutes(){
  String expected=null;
  for(int speed:new int[]{1,2,4}){GameView v=interactive(420,840);MemoryPreferences disk=Context.namedPreferences.get(OnlineDemoSaveStore.FILE);MockOnlineWorldRepository repo=allianceRepo(disk);String event=firstEvent(repo,true);repo.startOperation("online_job_1",event,fighters(1),Arrays.asList("demo_ember"),7,true);clock=new FrameClock();v=new GameView(new Context(),persistent(disk),clock);v.game.rnd=new Quiet();v.game.speed=speed;v.game.paused=false;radio(v);int minute=v.onlineWorld.state.gameplay.combat.expedition("online_job_1").elapsedMinutes;for(int s=0;s<10;s++){for(int f=0;f<60;f++)frame(v,16_666_667);v.tick.run();}require(v.onlineWorld.state.gameplay.combat.expedition("online_job_1").elapsedMinutes==minute+10*speed,"x"+speed+" operation advances by actual game minutes");String animation=Double.toString(v.onlineWorld.state.animationSeconds);if(expected==null)expected=animation;else require(expected.equals(animation),"event pulses use identical real frame time at each speed");v.game.paused=true;long paused=v.onlineWorld.state.gameplay.civic.minute;String solo=snapshot(v);for(int i=0;i<4;i++)v.tick.run();require(paused==v.onlineWorld.state.gameplay.civic.minute&&solo.equals(snapshot(v)),"pause stops schedule and operation without solo effects");
  }
  double target=-1;for(int fps:new int[]{15,30,60,120}){GameView v=interactive(420,840);MemoryPreferences disk=Context.namedPreferences.get(OnlineDemoSaveStore.FILE);MockOnlineWorldRepository r=allianceRepo(disk);String event=firstEvent(r,true);r.startOperation("online_job_1",event,fighters(1),Arrays.asList("demo_ember"),7,true);clock=new FrameClock();v=new GameView(new Context(),persistent(disk),clock);radio(v);for(int i=0;i<40;i++)v.onlineWorld.advanceMinute();for(int f=1;f<=fps;f++){clock.now=f*1_000_000_000L/fps;draw(v);}double p=v.onlineWorld.civicPanel.routes.get("online_job_1").progress;if(target<0)target=p;else require(Math.abs(target-p)<1e-8,"route smoothing is independent of frame rate "+fps);}
 }
 public static void main(String[] args){alliances();schedule();operations();lifecycleEdges();persistenceAndFailure();civicUi();gameClockAndRoutes();System.out.println("PASS: "+checks+" ONLINE 0.4 assertions; named alliance/invitations/thresholds, five scheduled event types/expiry/debug cooldown, shared fighter/ally assignments, success-only exact contributions and old PvE awards, atomic completion failures, v1/v2/v3 migration, ten Canvas/input layouts and name keyboard, durable reports/route cleanup, independent visual clock and paused/scaled game time, unchanged solo data.");}
}
'''

def main():
    sources={"com/lastdom/game/"+p.name:p.read_text() for p in (fixtures.ROOT/fixtures.JAVA_PATH).glob("*.java")}
    sources["com/lastdom/game/R.java"]="package com.lastdom.game;public class R{public static class drawable{public static final int shelter_clean=1,shelter_full_scene=2;}}"
    engine="com/lastdom/game/OnlineCombatEngine.java"
    sources[engine]=sources[engine].replace('final class OnlineCombatEngine {','final class OnlineCombatEngine {static int calculations;').replace('    Objects.requireNonNull(tactic);','    calculations++;\n    Objects.requireNonNull(tactic);')
    fixtures.PROBE=PROBE
    with tempfile.TemporaryDirectory(prefix="online-alliance-") as directory:
        print(fixtures.run_version(Path(directory),"online04",sources).strip())

if __name__=="__main__":main()
