#!/usr/bin/env python3
"""ONLINE 0.3 actual pure engine, atomic repository/save migration, Canvas/input and frame clocks.
Android doubles do not establish physical-device rendering or measured FPS.
"""
import sys
sys.dont_write_bytecode=True
from pathlib import Path
import tempfile
import online_gameplay_regression as previous
import refactor_regression as fixtures

PROBE=previous.PROBE[:previous.PROBE.index(' public static void main(')]+r'''
 static List<String> fighters(int... indices){List<String> ids=new ArrayList<>();for(int i:indices)ids.add("radio_"+i);return ids;}
 static OnlineCombatSquad squad(OnlineBattleRepository.State state,int... indices){List<OnlineCombatSquad.Fighter> selected=new ArrayList<>();for(String id:fighters(indices))selected.add(state.fighter(id));return new OnlineCombatSquad(selected);}
 static String signature(OnlineCombatReport report){return OnlineCombatCodec.encode(new OnlineBattleRepository.State(OnlineCombatSquad.roster(),Arrays.asList(new OnlineBattleRepository.Battle("online_job_1","pvp_frontier",report,0,false)),Collections.emptyList(),2,true));}
 static long coopSeed(String zone,OnlineCombatSquad own,OnlineCombatSquad ally,boolean success){for(long seed=0;seed<10000;seed++)if(OnlineCoopExpedition.calculate("online_job_1",zone,"demo_beacon",own,ally,seed).success==success)return seed;throw new AssertionError("seed fixture");}
 static OnlineShelter site(OnlineWorldRepository repository,String id){return repository.load().shelters.stream().filter(s->s.id.equals(id)).findFirst().get();}
 static void seededEngine(){
  OnlineCombatEngine engine=new OnlineCombatEngine();OnlineBattleRepository.State initial=OnlineBattleRepository.State.initial();
  Set<String> ids=new HashSet<>();for(OnlineCombatSquad.Fighter f:initial.fighters)require(ids.add(f.id)&&f.health==100&&f.stamina==100&&!f.name.equals("Иван"),"six unique independent healthy demo fighters");
  for(int size=1;size<=3;size++)for(OnlineCombatRules.Tactic tactic:OnlineCombatRules.Tactic.values())for(long seed=0;seed<80;seed++) {
   List<OnlineCombatSquad.Fighter> selection=initial.fighters.subList(0,size);OnlineCombatSquad own=new OnlineCombatSquad(selection),enemy=OnlineCombatSquad.enemy("fixed");
   OnlineCombatReport a=engine.calculate(own,enemy,tactic,"pvp_frontier",seed),b=engine.calculate(own,enemy,tactic,"pvp_frontier",seed);
   require(signature(a).equals(signature(b)),"same input/seed/rules reproduces complete round sequence");
   require(a.actions.size()>0&&a.actions.size()<=OnlineCombatRules.MAX_ROUNDS*6,"combat ends within maximum rounds");
   int[] hp=new int[6];for(int i=0;i<size;i++)hp[i]=100;for(int i=0;i<3;i++)hp[3+i]=90;int previousRound=0;
   for(OnlineCombatReport.Action action:a.actions){int index=(action.playerAttack?3:0)+action.target,actor=(action.playerAttack?0:3)+action.actor;
    require(hp[actor]>0&&hp[index]==action.before&&action.round>=previousRound,"only live actors and current target state");require(action.after==Math.max(0,action.before-Math.max(1,action.attack-action.blocked)),"damage and defense agree with round transition");hp[index]=action.after;previousRound=action.round;
    require(action.after>=0&&action.after<action.before&&action.round<=12,"bounded health and rounds");
   }
   require(Arrays.equals(hp,a.health(a.actions.size())),"stored timeline replays final health exactly");for(OnlineCombatSquad.Fighter f:own.fighters)require(f.health==100&&f.stamina==100,"engine never mutates its inputs");
  }
  OnlineCombatSquad.Fighter fighter=initial.fighters.get(1);
  require(OnlineCombatRules.attack(fighter,100,OnlineCombatRules.Tactic.AGGRESSIVE,100)>OnlineCombatRules.attack(fighter,100,OnlineCombatRules.Tactic.CAUTIOUS,100),"aggressive increases attack");require(OnlineCombatRules.defense(fighter,OnlineCombatRules.Tactic.CAUTIOUS,"pvp_frontier")>OnlineCombatRules.defense(fighter,OnlineCombatRules.Tactic.AGGRESSIVE,"pvp_frontier"),"cautious increases defense");require(OnlineCombatRules.attack(fighter,30,OnlineCombatRules.Tactic.BALANCED,100)<OnlineCombatRules.attack(fighter,100,OnlineCombatRules.Tactic.BALANCED,100),"injury decreases attack");
  OnlineCombatSquad weak=new OnlineCombatSquad(Arrays.asList(new OnlineCombatSquad.Fighter("weak_a","А","Тест",100,100,1,40,OnlineCombatSquad.Specialization.MEDIC))),other=new OnlineCombatSquad(Arrays.asList(new OnlineCombatSquad.Fighter("weak_b","Б","Тест",100,100,1,40,OnlineCombatSquad.Specialization.MEDIC)));
  OnlineCombatReport limit=engine.calculate(weak,other,OnlineCombatRules.Tactic.BALANCED,"pvp_frontier",77);require(limit.actions.get(limit.actions.size()-1).round==12&&limit.outcome==OnlineCombatReport.Outcome.DRAW,"round limit resolves equal remaining HP as draw");
  try{engine.calculate(weak,other,OnlineCombatRules.Tactic.BALANCED,"safe_north",1);throw new AssertionError("safe-zone combat");}catch(IllegalArgumentException expected){checks++;}
  try{new OnlineCombatSquad(Arrays.asList(fighter,fighter));throw new AssertionError("duplicate squad");}catch(IllegalArgumentException expected){checks++;}
 }
 static void pvpAtomicAndBusy(){
  MemoryPreferences disk=new MemoryPreferences();MockOnlineWorldRepository repo=persistent(disk);String before=ledger(repo);String id=repo.gameplay().combat.requestId();
  require(!repo.startPvp(id,"pvp_frontier",fighters(1,2,3),OnlineCombatRules.Tactic.BALANCED,42,false).success,"PvP denied without confirmation");
  for(String zone:Arrays.asList("safe_north","safe_south","pve_industry","pve_infected","missing"))require(!repo.startPvp(id,zone,fighters(1,2,3),OnlineCombatRules.Tactic.BALANCED,42,true).success,"PvP denied outside PvP zone");
  for(List<String> selection:Arrays.asList(Collections.<String>emptyList(),fighters(1,2,3,4),fighters(1,1),Arrays.asList("missing")))require(!repo.startPvp(id,"pvp_frontier",selection,OnlineCombatRules.Tactic.BALANCED,42,true).success,"invalid squad denied");require(before.equals(ledger(repo))&&disk.commits==0,"all validation failures are atomic");
  require(repo.startPvp(id,"pvp_frontier",fighters(1,2,3),OnlineCombatRules.Tactic.CAUTIOUS,42,true).success,"confirmed battle starts");OnlineBattleRepository.Battle battle=repo.gameplay().combat.battle(id);int calculated=OnlineCombatEngine.calculations;String started=ledger(repo);
  require(!repo.startPvp(id,"pvp_frontier",fighters(1,2,3),OnlineCombatRules.Tactic.CAUTIOUS,99,true).success&&started.equals(ledger(repo)),"repeated command cannot reroll or create a battle");
  require(!repo.startCoop(repo.gameplay().combat.requestId(),"pve_industry","demo_beacon",fighters(1),5,true).success&&!repo.recover("radio_1").success,"busy fighter cannot expedition or recover");
  require(repo.startCoop(repo.gameplay().combat.requestId(),"pve_industry","demo_beacon",fighters(4,5,6),5,true).success,"disjoint squad may run a cooperative task during combat");
  for(int i=0;i<battle.report.durationSeconds()-1;i++)repo.advanceSecond();require(repo.gameplay().combat.fighter("radio_1").health==100&&repo.gameplay().combat.busy("radio_1"),"combat effects wait for actual completion and hold assignment");
  MockOnlineWorldRepository loaded=persistent(disk);require(ledger(loaded).equals(ledger(repo))&&OnlineCombatEngine.calculations==calculated,"reload restores saved actions without recalculating engine");repo=loaded;repo.advanceSecond();battle=repo.gameplay().combat.battle(id);require(battle.effectsApplied&&!battle.active(),"combat finishes and applies effects once");int[] hp=battle.report.health(battle.report.actions.size());for(int i=0;i<3;i++)require(repo.gameplay().combat.fighter("radio_"+(i+1)).health==hp[i]&&repo.gameplay().combat.fighter("radio_"+(i+1)).stamina==88&&!repo.gameplay().combat.busy("radio_"+(i+1)),"exact final HP/stamina and unlock");
  String finished=ledger(repo);require(!repo.advanceSecond()&&finished.equals(ledger(repo)),"completed combat has no repeat effects");require(persistent(disk).gameplay().combat.battle(id).effectsApplied,"completion flag survives restart");
  require(repo.execute("ember_water",OnlineWorldGameplay.Kind.TRADE).success&&repo.gameplay().combat.battles.size()==1,"ONLINE 0.2 trade retains fighters/reports/active coop");repo.preparePvp("pvp_frontier",true);repo.disablePvp();require(repo.gameplay().combat.expeditions.size()==1,"old consent toggle cannot discard battle state");
  for(int i=0;i<24;i++)repo.advanceSecond();require(persistent(disk).gameplay().combat.expeditions.size()==1,"old delivery progress never resets battle storage");
 }
 static void coopRewardsAndAllies(){
  for(String zone:Arrays.asList("pve_industry","pve_infected"))for(boolean success:new boolean[]{false,true})for(int size=1;size<=3;size++) {
   MemoryPreferences disk=new MemoryPreferences();MockOnlineWorldRepository repo=persistent(disk);List<String> selection=fighters(size==1?new int[]{1}:size==2?new int[]{1,2}:new int[]{1,2,3});OnlineCombatSquad own=squad(repo.gameplay().combat,size==1?new int[]{1}:size==2?new int[]{1,2}:new int[]{1,2,3}),ally=OnlineCombatSquad.ally(site(repo,"demo_beacon"));long seed=coopSeed(zone,own,ally,success);String id=repo.gameplay().combat.requestId();
   require(!repo.startCoop(id,zone,"demo_beacon",selection,seed,false).success,"coop requires confirmation");require(repo.startCoop(id,zone,"demo_beacon",selection,seed,true).success,"start seeded coop");OnlineCoopExpedition e=repo.gameplay().combat.expedition(id);require(e.success==success&&e.durationMinutes==(zone.equals("pve_industry")?90:150),"persisted seeded outcome and configured duration");
   OnlineInventory inventory=repo.gameplay().inventory;require(!repo.startCoop(id,zone,"demo_beacon",selection,seed,true).success,"repeated send rejected");require(!repo.startCoop(repo.gameplay().combat.requestId(),zone,"demo_beacon",fighters(6),seed,true).success,"same virtual ally cannot join two active missions");
   for(int i=0;i<e.durationMinutes-1;i++)repo.advanceMinute();require(!repo.gameplay().combat.expedition(id).rewardApplied,"no grant before game-minute completion");for(OnlineInventory.Resource resource:OnlineInventory.Resource.values())require(inventory.amount(resource)==repo.gameplay().inventory.amount(resource),"no early resource grant");
   String saved=ledger(repo);MockOnlineWorldRepository restored=persistent(disk);require(saved.equals(ledger(restored)),"last active minute restores exactly");restored.advanceMinute();e=restored.gameplay().combat.expedition(id);require(e.rewardApplied&&!e.active(),"completion and grant flag committed together");
   for(OnlineInventory.Resource resource:OnlineInventory.Resource.values())require(restored.gameplay().inventory.amount(resource)==inventory.amount(resource)+e.loot.amount(resource),"exactly one demo grant per resource");
   for(int i=0;i<size;i++){OnlineCombatSquad.Fighter f=restored.gameplay().combat.fighter(selection.get(i));require(f.health==100-e.healthLoss.get(i)&&f.stamina==100-e.staminaCost&&!restored.gameplay().combat.busy(f.id),"bounded injuries/stamina and release at coop completion");}
   String completed=ledger(restored);for(int i=0;i<10;i++){restored.advanceMinute();restored.advanceSecond();restored.gameplay().combat.expedition(id);}
   require(completed.equals(ledger(restored))&&completed.equals(ledger(persistent(disk))),"reopen/restart/ticks cannot duplicate loot or injuries");
  }
  MockOnlineWorldRepository repo=new MockOnlineWorldRepository();OnlineCombatSquad own=squad(repo.gameplay().combat,1,2,3),weak=OnlineCombatSquad.ally(site(repo,"demo_outpost")),strong=OnlineCombatSquad.ally(site(repo,"demo_beacon"));int weakChance=OnlineCombatRules.coopChance("pve_industry",own,weak),strongChance=OnlineCombatRules.coopChance("pve_industry",own,strong);require(strongChance>weakChance,"ally's real stats improve success chance");long chosen=0;while(true){int roll=new Random(chosen).nextInt(100);if(roll>=weakChance&&roll<strongChance)break;chosen++;}require(!OnlineCoopExpedition.calculate("x","pve_industry","demo_outpost",own,weak,chosen).success&&OnlineCoopExpedition.calculate("x","pve_industry","demo_beacon",own,strong,chosen).success,"same seed genuinely changes outcome with stronger ally");
  for(OnlineShelter shelter:repo.load().shelters){OnlineCombatSquad ally=OnlineCombatSquad.ally(shelter);OnlineCoopExpedition e=OnlineCoopExpedition.calculate("x","pve_industry",shelter.id,own,ally,5);require(e.allyContribution>0&&e.allyContribution<100&&e.chance>=10&&e.chance<=95,"all four allies have real contribution and bounded chance");}
  require(!repo.startCoop("online_job_1","safe_north","demo_beacon",fighters(1),0,true).success&&!repo.startCoop("online_job_1","pve_industry","missing",fighters(1),0,true).success,"invalid PvE target/ally denied");
 }
 static void atomicCompletionFailuresAndMigration(){
  for(boolean applied:new boolean[]{false,true}){
   FailingPreferences disk=new FailingPreferences();MockOnlineWorldRepository repo=persistent(disk);OnlineCombatSquad own=squad(repo.gameplay().combat,1),ally=OnlineCombatSquad.ally(site(repo,"demo_beacon"));long seed=coopSeed("pve_industry",own,ally,true);repo.startCoop("online_job_1","pve_industry","demo_beacon",fighters(1),seed,true);for(int i=0;i<89;i++)repo.advanceMinute();OnlineCoopExpedition e=repo.gameplay().combat.expedition("online_job_1");String before=ledger(repo);int old=repo.gameplay().inventory.amount(OnlineInventory.Resource.MATERIALS);disk.fail=true;disk.applyThenFail=applied;require(!repo.advanceMinute()&&before.equals(ledger(repo)),"failed completion does not publish partial grant or fighter damage");disk.fail=false;MockOnlineWorldRepository recovered=persistent(disk);require(recovered.writable(),"atomic old or completed state loads");if(!applied)recovered.advanceMinute();require(recovered.gameplay().inventory.amount(OnlineInventory.Resource.MATERIALS)==old+e.loot.amount(OnlineInventory.Resource.MATERIALS),"uncertain I/O gives exactly one grant after recovery");String complete=ledger(recovered);recovered.advanceMinute();require(complete.equals(ledger(recovered)),"no second grant after completion retry");
  }
  MemoryPreferences disk=new MemoryPreferences();MockOnlineWorldRepository repo=persistent(disk);repo.execute("ember_water",OnlineWorldGameplay.Kind.TRADE);repo.preparePvp("pvp_frontier",true);for(int i=0;i<7;i++)repo.advanceSecond();String old=disk.getString(OnlineDemoSaveStore.KEY,"");require(old.startsWith("1|"),"unchanged ONLINE 0.2 format before using new module");MockOnlineWorldRepository migrated=persistent(disk);require(migrated.gameplay().combat.fighters.size()==6&&migrated.gameplay().operations.get(0).elapsedSeconds==7&&migrated.gameplay().inventory.amount(OnlineInventory.Resource.FOOD)==25,"v1 migration preserves inventory/trade progress and creates healthy demo roster");
  migrated.startPvp("online_job_1","pvp_frontier",fighters(1,2,3),OnlineCombatRules.Tactic.BALANCED,42,true);String modern=disk.getString(OnlineDemoSaveStore.KEY,"");require(modern.startsWith("2|")&&persistent(disk).writable(),"versioned combined v2 save restores");
  for(String corrupt:Arrays.asList(modern.substring(0,modern.length()-2),modern.replaceFirst("25,","999,"),modern+"00")){MemoryPreferences bad=new MemoryPreferences();bad.values.put(OnlineDemoSaveStore.KEY,corrupt);MockOnlineWorldRepository invalid=persistent(bad);require(!invalid.writable()&&invalid.load().connection==OnlineWorldState.Connection.ERROR&&bad.getString(OnlineDemoSaveStore.KEY,"").equals(corrupt),"corrupt combat save fails closed without resetting demo or solo resources");}
  for(int i=0;i<30;i++)migrated.advanceSecond();OnlineCombatSquad.Fighter f=migrated.gameplay().combat.fighter("radio_1");int hp=f.health,stamina=f.stamina,med=migrated.gameplay().inventory.amount(OnlineInventory.Resource.MEDICINE),water=migrated.gameplay().inventory.amount(OnlineInventory.Resource.WATER);require(migrated.recover(f.id).success,"idle injured fighter can recover using demo supplies");f=migrated.gameplay().combat.fighter(f.id);require(f.health==Math.min(100,hp+35)&&f.stamina==Math.min(100,stamina+OnlineCombatRules.RECOVER_STAMINA)&&migrated.gameplay().inventory.amount(OnlineInventory.Resource.MEDICINE)==med-1&&migrated.gameplay().inventory.amount(OnlineInventory.Resource.WATER)==water-1,"exact bounded recovery and atomic cost");require(ledger(migrated).equals(ledger(persistent(disk))),"fighter recovery survives restart");
  MockOnlineWorldRepository fresh=new MockOnlineWorldRepository();String before=ledger(fresh);require(!fresh.recover("radio_1").success&&before.equals(ledger(fresh)),"full-health full-stamina recovery spends nothing");
 }

 static void specializationAndRecoveryGuards(){
  MockOnlineWorldRepository repo=new MockOnlineWorldRepository();OnlineCombatSquad ally=OnlineCombatSquad.ally(site(repo,"demo_outpost"));
  OnlineCombatSquad mechanic=new OnlineCombatSquad(Arrays.asList(new OnlineCombatSquad.Fighter("m","М","Механик",100,100,15,7,OnlineCombatSquad.Specialization.MECHANIC))),engineer=new OnlineCombatSquad(Arrays.asList(new OnlineCombatSquad.Fighter("e","И","Инженер",100,100,15,7,OnlineCombatSquad.Specialization.ENGINEER))),medic=new OnlineCombatSquad(Arrays.asList(new OnlineCombatSquad.Fighter("d","В","Врач",100,100,15,7,OnlineCombatSquad.Specialization.MEDIC)));
  for(long seed=0;seed<20;seed++){
   OnlineCoopExpedition m=OnlineCoopExpedition.calculate("m","pve_industry","demo_outpost",mechanic,ally,seed),e=OnlineCoopExpedition.calculate("e","pve_industry","demo_outpost",engineer,ally,seed),d=OnlineCoopExpedition.calculate("d","pve_industry","demo_outpost",medic,ally,seed);
   require(m.chance==e.chance&&e.chance==d.chance&&m.success==e.success,"profession comparison holds stats/seed constant");if(m.success)require(m.loot.amount(OnlineInventory.Resource.MATERIALS)==(int)Math.ceil(e.loot.amount(OnlineInventory.Resource.MATERIALS)*1.15),"mechanic applies real +15% material bonus once");require(d.healthLoss.get(0)==e.healthLoss.get(0)*75/100,"doctor applies real damage reduction once");
  }
  OnlineCombatSquad tired=new OnlineCombatSquad(Arrays.asList(engineer.fighters.get(0).condition(20,20)));require(OnlineCombatRules.coopChance("pve_industry",tired,ally)<OnlineCombatRules.coopChance("pve_industry",engineer,ally),"low HP/stamina really reduce PvE chance");
  MemoryPreferences disk=new MemoryPreferences();MockOnlineWorldRepository persisted=persistent(disk);persisted.startPvp("online_job_1","pvp_frontier",fighters(1),OnlineCombatRules.Tactic.BALANCED,42,true);for(int i=0;i<30;i++)persisted.advanceSecond();OnlineWorldGameplay.Data data=persisted.gameplay();OnlineWorldGameplay.Data empty=new OnlineWorldGameplay.Data(new OnlineInventory(Collections.emptyMap()),data.offers,data.operations,data.reputation,data.pvpZoneId,data.combat);disk.values.put(OnlineDemoSaveStore.KEY,OnlineDemoSaveStore.encode(empty));MockOnlineWorldRepository shortage=persistent(disk);String before=ledger(shortage);require(!shortage.recover("radio_1").success&&before.equals(ledger(shortage)),"recovery with no demo medicine/water has no cost or partial healing");
 }
 static void panelRow(GameView v,OnlineCombatPanelController.Action action,String id){OnlineCombatPanelController p=v.onlineWorld.combatPanel;OnlineWorldGeometry g=geometry(v);draw(v);List<OnlineCombatPanelController.Row> rows=p.rows();int index=-1;for(int i=0;i<rows.size();i++)if(rows.get(i).action==action&&(id.isEmpty()||rows.get(i).id.equals(id))){index=i;break;}require(index>=0,"row exists: "+action+" "+id);p.scroll=Math.min(Math.max(0,p.contentHeight-(int)(g.contentBottom-g.contentTop+12)),p.layout.top(index));float y=g.contentTop-12+p.layout.top(index)-p.scroll+16;tap(v,120,y);draw(v);}
 static void newPanelsAndIsolation(){
  for(int width:new int[]{420,840})for(int height:new int[]{360,500,640,840,1200}) {
   GameView v=interactive(width,height);radio(v);v.game.paused=true;String solo=snapshot(v);OnlineWorldGeometry g=geometry(v);clickZone(v,v.onlineWorld.state.zones.get(4));draw(v);tap(v,315,g.panelTop+30);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.PVP_PREP,"PvP zone combat entry");draw(v);text(draw(v),"ПОДГОТОВКА PvP");
   tap(v,180,g.panelBottom-90);require(v.onlineWorld.state.gameplay.combat.battles.isEmpty(),"empty selection cannot start");for(int i=1;i<=3;i++)panelRow(v,OnlineCombatPanelController.Action.FIGHTER,"radio_"+i);panelRow(v,OnlineCombatPanelController.Action.FIGHTER,"radio_4");require(v.onlineWorld.combatPanel.selected.size()==3,"fourth fighter denied");
   panelRow(v,OnlineCombatPanelController.Action.TACTIC,"");require(v.onlineWorld.combatPanel.tactic==OnlineCombatRules.Tactic.AGGRESSIVE,"tactic chosen before consent");tap(v,180,g.panelBottom-90);require(v.onlineWorld.combatPanel.confirming&&v.onlineWorld.state.gameplay.combat.battles.isEmpty(),"first confirmation opens final danger warning");draw(v);text(draw(v),"ПОДТВЕРЖДЕНИЕ PvP");
   tap(v,180,g.panelBottom-40);require(!v.onlineWorld.combatPanel.confirming&&v.onlineWorld.state.gameplay.combat.battles.isEmpty(),"refusal starts no combat");tap(v,180,g.panelBottom-90);tap(v,180,g.panelBottom-90);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.BATTLE&&v.onlineWorld.state.gameplay.combat.battles.size()==1,"second explicit confirmation starts stored battle");draw(v);text(draw(v),"ДЕМО-СТОЛКНОВЕНИЕ");String id=v.onlineWorld.combatPanel.reportId;int calls=OnlineCombatEngine.calculations;
   v.onlineWorld.combatPanel.open(OnlineWorldState.Panel.COMBAT_HISTORY);for(OnlineCombatPanelController.Row row:v.onlineWorld.combatPanel.rows())if(row.action==OnlineCombatPanelController.Action.REPORT)require(row.title.equals("PvP · Столкновение")&&row.detail.equals("Бой продолжается"),"history does not reveal the precomputed outcome before combat ends");v.onlineWorld.combatPanel.showReport(id);
   for(int second=0;second<30;second++){for(int f=0;f<15;f++)frame(v,66_666_667);v.tick.run();}require(v.onlineWorld.state.gameplay.combat.battle(id).effectsApplied,"battle ends under existing host timer");String saved=ledger(persistent(Context.namedPreferences.get(OnlineDemoSaveStore.FILE)));v.onlineWorld.combatPanel.showReport(id);tap(v,180,g.panelBottom-90);for(int f=0;f<30;f++)frame(v,16_666_667);require(OnlineCombatEngine.calculations==calls&&saved.equals(OnlineDemoSaveStore.encode(v.onlineWorld.state.gameplay)),"replaying animation grants no resources and invokes no calculation");
   require(solo.equals(snapshot(v)),"combat, replay and real-time demo ticks preserve every save_v02 resource/resident/system");GameView loaded=new GameView(new Context());require(saved.equals(OnlineDemoSaveStore.encode(loaded.onlineWorld.state.gameplay))&&solo.equals(snapshot(loaded)),"default Android wiring restores combat without touching solo progress");
   v.onlineWorld.closeCard();tap(v,340,35);draw(v);tap(v,315,g.panelTop+30);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.ROSTER,"inventory opens fighter roster");draw(v);text(draw(v),"ДЕМО-БОЙЦЫ");tap(v,300,g.panelBottom-90);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.COMBAT_HISTORY,"saved reports accessible via roster");draw(v);panelRow(v,OnlineCombatPanelController.Action.REPORT,id);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.BATTLE,"completed combat reopened from durable history");
   v.onlineWorld.closeCard();clickZone(v,v.onlineWorld.state.zones.get(2));tap(v,315,g.panelTop+30);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.COOP_PREP,"existing PvE-zone opens co-op");panelRow(v,OnlineCombatPanelController.Action.FIGHTER,"radio_4");panelRow(v,OnlineCombatPanelController.Action.ALLY,"");tap(v,180,g.panelBottom-90);tap(v,180,g.panelBottom-90);require(v.onlineWorld.state.panel==OnlineWorldState.Panel.COOP_REPORT,"confirmed co-op opens its active report");draw(v);text(draw(v),"ОТЧЁТ PvE");
   if(v.onlineWorld.combatPanel.contentHeight>g.contentBottom-g.contentTop+12){v.onlineWorld.combatPanel.scroll=0;v.onTouchEvent(new MotionEvent(150*v.scale,(g.contentBottom-4)*v.scale,MotionEvent.ACTION_DOWN));v.onTouchEvent(new MotionEvent(150*v.scale,(g.contentTop-40)*v.scale,MotionEvent.ACTION_MOVE));v.onTouchEvent(new MotionEvent(150*v.scale,(g.panelBottom-90)*v.scale,MotionEvent.ACTION_UP));require(v.onlineWorld.combatPanel.scroll>0&&v.onlineWorld.state.panel==OnlineWorldState.Panel.COOP_REPORT,"long report scrolls without footer action");}
   require(solo.equals(snapshot(v)),"co-op sending/scrolling also leaves solo resources unchanged");
  }
 }
 static void speedClocksAndBackground(){
  String visualReference=null;
  for(int speed:new int[]{1,2,4}) {
   GameView v=interactive(420,840);radio(v);v.game.speed=speed;v.game.paused=false;
   MemoryPreferences disk=Context.namedPreferences.get(OnlineDemoSaveStore.FILE);MockOnlineWorldRepository repo=persistent(disk);require(repo.startPvp("online_job_1","pvp_frontier",fighters(1,2,3),OnlineCombatRules.Tactic.BALANCED,7,true).success,"animation clock fixture");require(repo.startCoop("online_job_2","pve_industry","demo_beacon",fighters(4,5,6),7,true).success,"simultaneous coop clock fixture");
   clock=new FrameClock();v=new GameView(new Context(),persistent(disk),clock);v.game.rnd=new Quiet();v.game.speed=speed;radio(v);v.onlineWorld.combatPanel.showReport("online_job_1");int minute=v.game.gameMinute;
   for(int second=0;second<10;second++){for(int frame=0;frame<60;frame++)frame(v,16_666_667);v.tick.run();}
   require(v.game.gameMinute==minute+speed*10&&v.onlineWorld.state.gameplay.combat.expedition("online_job_2").elapsedMinutes==speed*10,"coop uses actual accelerated game minutes");String visual=Double.toString(v.onlineWorld.combatPanel.replaySeconds);if(visualReference==null)visualReference=visual;else require(visualReference.equals(visual),"battle replay same real-time duration at x"+speed);
   v.game.paused=true;int elapsed=v.onlineWorld.state.gameplay.combat.expedition("online_job_2").elapsedMinutes;String solo=snapshot(v);for(int i=0;i<3;i++)v.tick.run();require(v.onlineWorld.state.gameplay.combat.expedition("online_job_2").elapsedMinutes==elapsed&&solo.equals(snapshot(v)),"pause freezes co-op and solo needs/economy");
   v.onlineWorld.leave();v.game.screen=GameView.HOME;v.game.paused=false;for(int i=0;i<150;i++)v.tick.run();require(v.onlineWorld.state.gameplay.combat.expedition("online_job_2").rewardApplied,"coop continues and completes across tabs");String saved=OnlineDemoSaveStore.encode(v.onlineWorld.state.gameplay);GameView restarted=new GameView(new Context());require(saved.equals(OnlineDemoSaveStore.encode(restarted.onlineWorld.state.gameplay)),"completed jobs/loot/conditions restore on relaunch");
  }
  for(int fps:new int[]{15,30,60,120}){
   GameView v=interactive(420,640);MemoryPreferences disk=Context.namedPreferences.get(OnlineDemoSaveStore.FILE);persistent(disk).startPvp("online_job_1","pvp_frontier",fighters(1,2,3),OnlineCombatRules.Tactic.BALANCED,42,true);clock=new FrameClock();v=new GameView(new Context(),persistent(disk),clock);v.game.rnd=new Quiet();radio(v);v.onlineWorld.combatPanel.showReport("online_job_1");
   v.onlineWorld.combatPanel.replaySeconds=0;for(int frame=1;frame<=fps;frame++){clock.now=frame*1_000_000_000L/fps;draw(v);}require(Math.abs(v.onlineWorld.combatPanel.replaySeconds-1)<1e-8,"battle animation frame-rate independent "+fps);
   double before=v.onlineWorld.combatPanel.replaySeconds;clock.now+=60_000_000_000L;draw(v);require(before==v.onlineWorld.combatPanel.replaySeconds,"long background gap does not skip combat replay");
  }
 }
 public static void main(String[] args){seededEngine();pvpAtomicAndBusy();coopRewardsAndAllies();atomicCompletionFailuresAndMigration();specializationAndRecoveryGuards();newPanelsAndIsolation();speedClocksAndBackground();System.out.println("PASS: "+checks+" ONLINE 0.3 assertions; seeded bounded combat/all tactics, explicit PvP-only consent, busy fighter/ally guards, cooperative successes/failures/ally contribution, exactly-once atomic rewards and injuries, v1 migration/v2 recovery/I/O failures, healing costs, read-only report replay, ten scaled Canvas/input layouts, independent animation and accelerated/paused game-minute expeditions, unchanged save_v02.");}
}
'''

def main():
    sources={"com/lastdom/game/"+p.name:p.read_text() for p in (fixtures.ROOT/fixtures.JAVA_PATH).glob("*.java")}
    engine="com/lastdom/game/OnlineCombatEngine.java"
    sources[engine]=sources[engine].replace('final class OnlineCombatEngine {','final class OnlineCombatEngine {static int calculations;').replace('    Objects.requireNonNull(tactic);','    calculations++;\n    Objects.requireNonNull(tactic);')
    sources["com/lastdom/game/R.java"]="package com.lastdom.game;public class R{public static class drawable{public static final int shelter_clean=1,shelter_full_scene=2;}}"
    fixtures.PROBE=PROBE
    with tempfile.TemporaryDirectory(prefix="online-combat-") as directory:
        print(fixtures.run_version(Path(directory),"online03",sources).strip())

if __name__=="__main__":main()
