#!/usr/bin/env python3
"""Real STORY1.2-created saves and faction/controller/expedition/Canvas regression."""
import sys
sys.dont_write_bytecode=True
from pathlib import Path
import tempfile,base64,json
import story_investigation_regression as investigation
import story_regression as base
import refactor_regression as fixtures
PREFIX=investigation.PROBE[:investigation.PROBE.index(' static void migrations()')]
PREFIX += '\n'.join(line for line in base.PROBE.splitlines() if line.startswith(' static Expedition launch(') or line.startswith(' static GameView decodeReady('))+'\n'
PLAY=r'''
 static GameView completed(boolean signal,boolean documents){GameView v=decodeReady();require(v.game.storyController.decode(v.game.people.get(0).id).isEmpty(),"old actual decoding");minute(v,60);v.game.storyController.read(StoryConfig.DECODED.id);require(v.game.storyController.choose(signal?StoryConfig.SHARE.id:StoryConfig.SECRET.id,true).isEmpty(),"first decision");for(String id:new String[]{"voices.intro","voices.residents","voices.eva",signal?"voices.public":"voices.secret","voices.hook","dawn.intro"})finish(v,id,0);v=returnPlot(v,StoryInvestigationConfig.ARCHIVE,true);finish(v,"dawn.archive_review",0);v=returnPlot(v,StoryInvestigationConfig.LAB,true);finish(v,"dawn.lab_review",0);v=returnPlot(v,StoryInvestigationConfig.ENTRANCE,true);finish(v,"dawn.entrance_review",0);require(v.game.storyController.investigation.choose(documents?StoryInvestigationConfig.SHARE:StoryInvestigationConfig.KEEP,true).isEmpty(),"old second decision");v.game.paused=true;v.game.save();return v;}
'''
LEGACY=PREFIX+PLAY+r'''
 public static void main(String[]args){for(boolean signal:new boolean[]{true,false})for(boolean docs:new boolean[]{true,false}){completed(signal,docs);System.out.println("SAVE");for(Map.Entry<String,Object> e:Context.preferences.values.entrySet())System.out.println("VALUE:"+e.getKey()+":"+e.getValue().getClass().getSimpleName()+":"+Base64.getEncoder().encodeToString(e.getValue().toString().getBytes(java.nio.charset.StandardCharsets.UTF_8)));}}
}
'''
PROBE=PREFIX+PLAY+r'''
 static GameView contacts(){GameView v=completed(true,true);require(v.game.story.factions.started,"new completion starts immediately without tick");require(!v.game.storyController.factions.choose(StoryFactionConfig.NONE,true).isEmpty(),"side blocked before all contacts");require(!v.game.expeditionController.start(StoryFactionConfig.ALL[0].locationId,ids(v,0)).isEmpty(),"contact required before mission");for(StoryFaction f:StoryFactionConfig.ALL)finish(v,f.contact.event.id,0);return v;}
 static void migrations(){int i=0;for(MemoryPreferences old:legacy()){Context.preferences=old;String first=old.getString("story1_decision",""),second=old.getString("story1_investigationDecision","");GameView v=loaded();StoryFactionState s=v.game.story.factions;require(s.started&&s.contacts.isEmpty(),"actual STORY1.2 save activates at load before tick");require(v.game.story.decisionId.equals(first)&&v.game.story.investigationDecision.equals(second),"both original decisions preserved");int a=first.equals(StoryConfig.SHARE.id)?1:-1,b=second.equals(StoryInvestigationConfig.SHARE)?1:-1;require(s.reputation.get(StoryFactionConfig.UNION)==10*a+10*b,"union both decisions");require(s.reputation.get(StoryFactionConfig.GARRISON)==-10*a-10*b,"garrison opposite stance");require(s.reputation.get(StoryFactionConfig.HEIRS)==5*b,"heirs document stance");require(v.game.food==old.getInt("food",-1)&&v.game.water==old.getInt("water",-1),"migration no economy changes");int logs=v.game.log.size();String online=OnlineDemoSaveStore.encode(v.onlineWorld.state.gameplay);v=restart(v);v.storyPanel.showJournal();v.game.storyController.restore();require(v.game.log.size()==logs&&v.game.story.factions.applied.size()==3,"initial reputation applied once on reopen and restart");require(online.equals(OnlineDemoSaveStore.encode(v.onlineWorld.state.gameplay)),"online state untouched");require(v.game.story.pendingMessage.equals(StoryFactionConfig.ALL[0].contact.event.id),"first representative available");String contact=StoryFactionConfig.ALL[0].contact.event.id;v.storyPanel.showMessage(contact);v.storyPanel.primaryAction();v.storyPanel.close();v=restart(v);require(v.game.story.dialogueSteps.get(contact)==1&&!v.game.story.factions.contacts.contains(StoryFactionConfig.UNION),"unfinished contact cursor survives close and restart");finish(v,contact,0);int applied=v.game.story.factions.applied.size();v=restart(v);v.storyPanel.showMessage(contact);v.storyPanel.primaryAction();require(v.game.story.factions.contacts.contains(StoryFactionConfig.UNION)&&v.game.story.factions.applied.size()==applied,"reopened contact no duplicated reputation");i++;}require(i==4,"four genuine old decision combinations");GameView v=fresh(420,840);v.game.storyController.factions.activate();require(!v.game.story.factions.started,"cannot start early");StoryRepository.load(v.game.story,legacy().get(0));v.storyPanel.showJournal();require(v.game.story.factions.started,"journal activates independently without tick");}
 static void missions(){GameView v=contacts();Resident busy=v.game.people.get(0);v.game.mats=100;specialistReady(v);require(v.game.roomUpgradeController.start(0,busy.id).isEmpty(),"actual builder starts");require(!v.game.expeditionController.start(StoryFactionConfig.ALL[1].locationId,ids(v,0)).isEmpty(),"builder barred from faction mission");v.game.roomUpgradeController.advanceMinute();v=contacts();String online=OnlineDemoSaveStore.encode(v.onlineWorld.state.gameplay);v.game.food=20;v.game.water=20;v.game.mats=15;v.game.rnd=new Random(){public double nextDouble(){return 0;}public int nextInt(int n){return n-1;}};
  for(StoryFaction f:StoryFactionConfig.ALL){v=returnPlot(v,f.locationId,false);require(!v.game.story.factions.completed.contains(f.id),"failure supports retry, no quest award");v=returnPlot(v,f.locationId,true);require(v.game.story.factions.completed.contains(f.id),"real expedition completes faction quest");require(v.game.story.objectives.contains("faction.done."+f.id),"shared quest objective");int reputation=v.game.story.factions.reputation.get(f.id),food=v.game.food,water=v.game.water,logs=v.game.log.size();v.game.storyController.factions.advanceMinute();v=restart(v);require(v.game.story.factions.reputation.get(f.id)==reputation&&v.game.food==food&&v.game.water==water&&v.game.log.size()==logs,"awards and humanitarian cost once");require(!v.game.expeditionController.start(f.locationId,ids(v,0)).isEmpty(),"completed mission not repeatable");}
  require(v.game.story.items.contains("faction.lost_protocol"),"technical protocol granted once");require(online.equals(OnlineDemoSaveStore.encode(v.onlineWorld.state.gameplay)),"quests leave demo inventory untouched");require(v.game.story.entranceInspected&&!v.game.storyController.expeditionReason(StoryInvestigationConfig.ENTRANCE).isEmpty(),"door still sealed and old quest preserved");
  v=contacts();v.game.food=0;v.game.water=0;v=returnPlot(v,StoryFactionConfig.ALL[0].locationId,true);require(!v.game.story.factions.completed.contains(StoryFactionConfig.UNION)&&v.game.story.factions.supplied.contains(StoryFactionConfig.UNION),"shortage stores delivery stage without negative resources");require(!v.game.storyController.factions.deliver(true).isEmpty(),"shortage blocks donation");v=restart(v);v.game.food=2;v.game.water=2;require(v.game.storyController.factions.deliver(true).isEmpty(),"later delivery permitted");require(v.game.food==0&&v.game.water==0,"precise moderate cost");require(!v.game.storyController.factions.deliver(true).isEmpty()&&v.game.food==0,"no duplicate cost");
 }
 static void decisions(){for(String side:new String[]{StoryFactionConfig.UNION,StoryFactionConfig.GARRISON,StoryFactionConfig.HEIRS,StoryFactionConfig.NONE}){GameView v=contacts();StoryFactionController c=v.game.storyController.factions;String first=v.game.story.decisionId,second=v.game.story.investigationDecision;require(!c.choose(side,false).isEmpty(),"explicit side confirmation");v.storyPanel.showJournal();draw(v);tap(v,180,v.storyRenderer.layout().primaryTop+28);require(v.storyPanel.mode==StoryPanelController.Mode.FACTION_CHOICE,"large primary opens four-choice panel");v.storyPanel.choiceId=side;v.storyPanel.primaryAction();require(v.game.story.factions.side.equals(side)&&v.game.story.flags.contains(StoryFactionConfig.FLAG+side),"separate side flag");Map<String,Integer> reputation=new LinkedHashMap<>(v.game.story.factions.reputation);require(!c.choose(StoryFactionConfig.NONE,true).isEmpty(),"cannot choose again");v=restart(v);require(v.game.story.factions.reputation.equals(reputation)&&v.game.story.factions.side.equals(side),"side and reputations persist");require(v.game.story.decisionId.equals(first)&&v.game.story.investigationDecision.equals(second),"old choices untouched");for(StoryFaction f:StoryFactionConfig.ALL){c=v.game.storyController.factions;c.change("test.upper."+f.id,f.id,Integer.MAX_VALUE,"test");require(c.state.reputation.get(f.id)==100,"upper bound");c.change("test.lower."+f.id,f.id,Integer.MIN_VALUE,"test");require(c.state.reputation.get(f.id)==-100,"lower bound");c.change("test.lower."+f.id,f.id,1000,"duplicate");require(c.state.reputation.get(f.id)==-100,"idempotent relationship action");}v=restart(v);require(v.game.story.factions.reputation.values().stream().allMatch(n->n==-100),"negative reputation survives persistence");}}
 static void ui(){for(int h:new int[]{640,840,1200}){GameView v=contacts();View.width=420;View.height=h;draw(v);v.storyPanel.showJournal();draw(v);require(v.storyPanel.rows.stream().anyMatch(r->r.text.contains("ФРАКЦИИ")),"journal faction section");for(StoryFaction f:StoryFactionConfig.ALL){v.storyPanel.journalAction("faction.map."+f.id);require(v.game.screen==GameView.CITY_MAP&&v.cityMap.focusedLocationId.equals(f.locationId),"visible quest navigation");CityMapLayout l=new CityMapLayout(v.H/v.scale);MapLocation m=v.game.expeditionController.location(f.locationId);tap(v,l.x(m.mapX),l.y(m.mapY));require(v.cityMap.selected()==m,"actual new point hit target");v.cityMap.closeSelection();}v.storyPanel.showMessage(StoryFactionConfig.ALL[0].contact.event.id);draw(v);StoryPanelLayout l=v.storyRenderer.layout();require(l.closeTop+56<=v.H/v.scale-80,"fixed accessible buttons above nav");}}
 public static void main(String[]args){migrations();missions();decisions();ui();System.out.println("PASS: "+checks+" STORY1.3 faction assertions; genuine STORY1.2 saves, four prior branches, three real quests and contacts, all side choices, bounded/idempotent reputation, humanitarian shortage and exact cost, once-only items, restarts and Canvas navigation, online isolation.");}
}
'''
def main():
 with tempfile.TemporaryDirectory(prefix='story13-') as directory:
  fixtures.PROBE=LEGACY
  old=fixtures.run_version(Path(directory),'story12',base.sources('745d784c2a1c43d2985735fcccdddcf9ee1f118d'));blocks=[]
  for line in old.splitlines():
   if line=='SAVE':blocks.append([])
   elif line.startswith('VALUE:'):
    _,key,kind,value=line.split(':',3);value=base64.b64decode(value).decode();method={'Integer':'putInt','Boolean':'putBoolean','String':'putString'}[kind];literal=json.dumps(value,ensure_ascii=False) if kind=='String' else value;blocks[-1].append(f'e.{method}({json.dumps(key)}, {literal});')
  assert len(blocks)==4
  method=' static List<MemoryPreferences> legacy(){List<MemoryPreferences> result=new ArrayList<>();MemoryPreferences p;SharedPreferences.Editor e;'
  for block in blocks:method+='p=new MemoryPreferences();e=p.edit();'+''.join(block)+'e.commit();result.add(p);'
  method+='return result;}'
  fixtures.PROBE=PROBE.replace(' public static void main(String[]args){migrations()',method+' public static void main(String[]args){migrations()')
  try:print(fixtures.run_version(Path(directory),'factions',base.sources()).strip())
  except __import__('subprocess').CalledProcessError as error:
   if error.output:print(error.output)
   raise
if __name__=='__main__':main()
