#!/usr/bin/env python3
"""STORY1.2 actual expedition/plot/dialogue/Canvas, with original STORY1.1.1 save migration."""
import sys
sys.dont_write_bytecode=True
from pathlib import Path
import tempfile, base64, json
import story_regression as base
import story_dialogue_regression as dialogues
import refactor_regression as fixtures
OLD='ea25b91e3f1601b3624981646144db961aa55c16'
PREFIX=dialogues.PROBE[:dialogues.PROBE.index(' static void branches()')]
LEGACY=base.PROBE[:base.PROBE.index(' public static void main(String[]args){triggerAndMessages()')]+r'''
 static List<MemoryPreferences> legacy(){return Collections.emptyList();}
 static void finish(GameView v,String id,int answer){StoryDialogue d=StoryDialogue.find(id);while(!v.game.story.completedDialogues.contains(id)){int step=v.game.storyController.step(d);require(v.game.storyController.continueDialogue(id,step,d.lines[step].responses.length==0?-1:answer).isEmpty(),"old dialogue advances");}}
 static void export(){System.out.println("SAVE");for(Map.Entry<String,Object> e:Context.preferences.values.entrySet()){Object v=e.getValue();System.out.println("VALUE:"+e.getKey()+":"+v.getClass().getSimpleName()+":"+Base64.getEncoder().encodeToString(v.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8)));}}
 public static void main(String[]args){for(boolean shared:new boolean[]{true,false}){GameView v=decodeReady();require(v.game.storyController.decode(v.game.people.get(0).id).isEmpty(),"actual old decoding");minute(v,60);v.game.storyController.read(StoryConfig.DECODED.id);require(v.game.storyController.choose(shared?StoryConfig.SHARE.id:StoryConfig.SECRET.id,true).isEmpty(),"actual old first decision");finish(v,"voices.intro",0);finish(v,"voices.residents",0);finish(v,"voices.eva",0);finish(v,shared?"voices.public":"voices.secret",0);v.game.paused=true;v.game.save();export();finish(v,"voices.hook",0);v.game.save();export();}}
}
'''
PROBE=PREFIX+r'''
 static GameView investigation(){GameView v=ready(true);finish(v,"voices.intro",0);finish(v,"voices.residents",0);finish(v,"voices.eva",0);finish(v,"voices.public",0);v.game.paused=true;finish(v,"voices.hook",0);require(v.game.story.investigation==StoryInvestigationController.Phase.EVA,"completion activates new chain without game tick");return v;}
 static GameView returnPlot(GameView v,String target,boolean success){
  for(Resident r:v.game.people){r.health=100;r.fatigue=0;r.hunger=10;r.thirst=10;r.morale=75;r.autoRecovery=false;r.resumeJob="";r.job="Материалы";}
  seeded(v,success?0:1);require(v.game.expeditionController.start(target,ids(v,0)).isEmpty(),"normal squad can launch plot target");Expedition e=v.game.expeditionController.active();String id=e.id;MapLocation m=v.game.expeditionController.location(target);int travel=ExpeditionConfig.oneWayMinutes(m);int research=ExpeditionConfig.explorationMinutes(m);int before=v.game.story.items.size();
  minute(v,travel/2);float progress=e.progress();v=restart(v);e=v.game.expeditionController.find(id);require(e.progress()==progress&&e.state()==Expedition.State.TRAVELING_TO_TARGET,"saved outgoing route exact");minute(v,travel-travel/2+research);
  require(e.state()==Expedition.State.AWAITING_RETURN,"research awaits player return");require(v.game.story.items.size()==before,"no narrative award before home");v=restart(v);e=v.game.expeditionController.find(id);require(v.game.story.attemptResults.get(id)==success,"one-time random result persisted");require(v.game.expeditionController.returnHome(id).isEmpty(),"normal return confirmation");minute(v,travel-1);require(v.game.story.items.size()==before&&e.state()==Expedition.State.RETURNING,"no item while travelling back");v=restart(v);e=v.game.expeditionController.find(id);minute(v,1);require(e.state()==Expedition.State.COMPLETED&&!v.game.isOnExpedition(v.game.people.get(0)),"actual complete releases real resident");int items=v.game.story.items.size(),logs=v.game.log.size();for(int i=0;i<5;i++){v.game.expeditionController.complete(e);v.game.storyController.advanceMinute();}require(v.game.story.items.size()==items&&v.game.log.size()==logs,"replayed completed expedition has no awards/events");return restart(v);
 }
 static void migrations(){int index=0;for(MemoryPreferences old:legacy()){
  Context.preferences=old;String decision=old.getString("story1_decision", "");int trust=old.getInt("story1_evaTrust",50);int prior=old.getInt("story1_voicesStage",0);GameView v=loaded();require(v.game.story.decisionId.equals(decision)&&v.game.story.evaTrust==trust,"old choice/trust preserved");require(v.game.paused&&v.game.story.items.contains(StoryConfig.CARRIER),"actual completed original expedition carrier and pause preserved");require(v.game.food==old.getInt("food",-1)&&v.game.water==old.getInt("water",-1)&&v.game.mats==old.getInt("mats",-1),"migration does not alter original inventories");
  require(v.game.story.investigation==(prior==6?StoryInvestigationController.Phase.EVA:StoryInvestigationController.Phase.DORMANT),"actual old completed/unfinished saves correctly gated at load");if(prior==6){require(v.game.story.pendingMessage.equals("dawn.intro")&&v.game.story.messages.contains("voices.eva"),"new message and historical dialogue both available");int logs=v.game.log.size();v=restart(v);v.storyPanel.showJournal();require(v.game.log.size()==logs&&Collections.frequency(v.game.story.messages,"dawn.intro")==1&&Context.preferences.getString("story1_investigation", "").equals("EVA"),"migration persisted once without tick");}
  index++;
 }require(index==4,"both branches completed and unfinished original saves");
 for(MemoryPreferences old:legacy()){if(old.getInt("story1_voicesStage",0)!=6)continue;GameView v=fresh(420,840);v.game.paused=true;StoryRepository.load(v.game.story,old);require(v.game.story.investigation==StoryInvestigationController.Phase.DORMANT,"old repository snapshot not automatically reconciled without lifecycle");v.storyPanel.showJournal();require(v.game.story.investigation==StoryInvestigationController.Phase.EVA,"journal independently activates without minute");}
 }
 static void lifecycle(boolean share){GameView v=investigation();String first=v.game.story.decisionId;int trust=v.game.story.evaTrust;String online=OnlineDemoSaveStore.encode(v.onlineWorld.state.gameplay);Set<String> oldFlags=new LinkedHashSet<>(v.game.story.flags);
  require(!v.game.storyController.investigation.visible(StoryInvestigationConfig.ARCHIVE),"archive waits for Eva dialogue");v.storyPanel.showMessage("dawn.intro");draw(v);StoryPanelLayout layout=v.storyRenderer.layout();tap(v,180,layout.primaryTop+28);require(v.game.story.dialogueSteps.get("dawn.intro")==1,"compact panel shares actual touch geometry");v.storyPanel.close();v=restart(v);require(v.game.story.dialogueSteps.get("dawn.intro")==1,"close/restart retains exact dialogue line");finish(v,"dawn.intro",0);
  require(v.cityMap.visibleLocations().stream().anyMatch(m->m.id.equals(StoryInvestigationConfig.ARCHIVE)),"archive truly visible on existing map");require(!v.game.expeditionController.start(StoryInvestigationConfig.LAB,ids(v,0)).isEmpty(),"lab cannot skip archive");
  v=returnPlot(v,StoryInvestigationConfig.ARCHIVE,false);require(!v.game.story.items.contains(StoryInvestigationConfig.DOCUMENTS)&&v.game.story.investigation==StoryInvestigationController.Phase.ARCHIVE,"failed archive supports retry without fake findings");v=returnPlot(v,StoryInvestigationConfig.ARCHIVE,true);require(v.game.story.items.containsAll(Arrays.asList(StoryInvestigationConfig.DOCUMENTS,StoryInvestigationConfig.CATASTROPHE,StoryInvestigationConfig.MENTION)),"archive returns three factual findings");require(!v.game.storyController.investigation.visible(StoryInvestigationConfig.LAB),"documents must be studied first");finish(v,"dawn.archive_review",0);
  MapLocation archive=v.game.expeditionController.location(StoryInvestigationConfig.ARCHIVE),lab=v.game.expeditionController.location(StoryInvestigationConfig.LAB);require(ExpeditionConfig.oneWayMinutes(lab)>ExpeditionConfig.oneWayMinutes(archive)&&ExpeditionConfig.explorationMinutes(lab)>ExpeditionConfig.explorationMinutes(archive),"lab longer and more dangerous");require(lab.risk==MapLocation.Risk.HIGH&&!lab.isLocked(),"lab unlocked after studying archive");
  v=returnPlot(v,StoryInvestigationConfig.LAB,true);require(v.game.story.items.containsAll(Arrays.asList(StoryInvestigationConfig.JOURNAL,StoryInvestigationConfig.NOTES,StoryInvestigationConfig.KEY)),"one journal notes and key fragment");require(v.game.storyController.investigation.visible(StoryInvestigationConfig.ENTRANCE),"key reveals entrance immediately");require(!v.game.expeditionController.start(StoryInvestigationConfig.ENTRANCE,ids(v,0)).isEmpty(),"analysis required before entrance expedition");
  Resident ivan=v.game.people.get(0);ivan.status=Resident.Status.ON_EXPEDITION;String unavailable=v.game.storyController.dialogueText(StoryInvestigationConfig.LAB_REVIEW,1);require(unavailable.contains("недоступен"),"absent analyst no fictional physical presence");finish(v,"dawn.lab_review",0);ivan.status=Resident.Status.HOME;v.game.save();
  v=returnPlot(v,StoryInvestigationConfig.ENTRANCE,true);require(v.game.story.entranceInspected&&v.game.storyController.investigation.description(StoryInvestigationConfig.ENTRANCE).contains("Гермодверь: закрыта"),"outer inspection leaves door sealed");finish(v,"dawn.entrance_review",0);String choice=share?StoryInvestigationConfig.SHARE:StoryInvestigationConfig.KEEP;require(!v.game.storyController.investigation.choose(choice,false).isEmpty(),"explicit confirmation required");v.storyPanel.showJournal();draw(v);StoryPanelLayout decisionLayout=v.storyRenderer.layout();tap(v,180,decisionLayout.primaryTop+28);require(v.storyPanel.mode==StoryPanelController.Mode.INVESTIGATION_CHOICE,"journal opens separate document decision panel");draw(v);int row=0;while(!v.storyPanel.rows.get(row).id.equals(choice))row++;v.storyPanel.scroll=v.storyRenderer.rowTop(row);draw(v);decisionLayout=v.storyRenderer.layout();tap(v,180,decisionLayout.contentTop+v.storyRenderer.rowTop(row)-v.storyPanel.scroll+20);require(v.storyPanel.choiceId.equals(choice)&&v.game.story.investigationDecision.isEmpty(),"actual touch selects without committing choice");tap(v,180,decisionLayout.primaryTop+28);require(v.game.story.investigationDecision.equals(choice),"fixed confirmation commits separate decision");int logs=v.game.log.size(),items=v.game.story.items.size();require(!v.game.storyController.investigation.choose(share?StoryInvestigationConfig.KEEP:StoryInvestigationConfig.SHARE,true).isEmpty(),"cannot change second decision");v=restart(v);v.storyPanel.showJournal();v.game.storyController.advanceMinute();require(v.game.story.investigation==StoryInvestigationController.Phase.COMPLETE&&v.game.story.investigationDecision.equals(choice),"completed phase/decision survive restart");require(v.game.story.decisionId.equals(first)&&v.game.story.evaTrust==trust&&v.game.story.flags.containsAll(oldFlags),"first decision and trust untouched");require(v.game.story.items.size()==items&&v.game.log.size()==logs,"completion never regrants finds or repeats log");require(!v.game.storyController.expeditionReason(StoryInvestigationConfig.ENTRANCE).isEmpty(),"no entry to next chapter or duplicate entrance mission");require(online.equals(OnlineDemoSaveStore.encode(v.onlineWorld.state.gameplay)),"online module remains isolated");
 }
 static void uiAndClock(){for(int width:new int[]{420,840})for(int height:new int[]{360,640,840,1200}){
  GameView v=investigation();View.width=width;View.height=height*width/420;draw(v);v.storyPanel.showMessage("dawn.intro");draw(v);StoryPanelLayout l=v.storyRenderer.layout();require(l.closeTop+56<=v.H/v.scale-80&&l.contentBottom>l.contentTop,"compact and long panels above nav on all sizes");if(height==1200)require(l.bottom-l.top<height-154,"short talk uses compact panel");finish(v,"dawn.intro",0);v.storyPanel.close();v.game.screen=GameView.CITY_MAP;CityMapLayout map=new CityMapLayout(v.H/v.scale);MapLocation archive=v.game.expeditionController.location(StoryInvestigationConfig.ARCHIVE);tap(v,map.x(archive.mapX),map.y(archive.mapY));require(v.cityMap.selected()==archive,"actual archive hitbox uses normalized map coordinates");v.cityMap.closeSelection();v.game.story.items.add(StoryInvestigationConfig.KEY);v.game.story.objectives.add("dawn.review");v.game.storyController.investigation.syncMap();for(String id:new String[]{StoryInvestigationConfig.LAB,StoryInvestigationConfig.ENTRANCE}){MapLocation point=v.game.expeditionController.location(id);tap(v,map.x(point.mapX),map.y(point.mapY));require(v.cityMap.selected()==point,"actual new marker distinct from preserved old markers");v.cityMap.closeSelection();}
 }
 for(int speed:new int[]{1,2,4}){GameView v=investigation();finish(v,"dawn.intro",0);for(Resident r:v.game.people){r.job="Материалы";r.fatigue=0;r.autoRecovery=false;}seeded(v,0);require(v.game.expeditionController.start(StoryInvestigationConfig.ARCHIVE,ids(v,0)).isEmpty(),"clock squad launch");v.game.speed=speed;Expedition e=v.game.expeditionController.active();v.tick.run();require(e.elapsedMinutes()==0,"pause freezes plot expedition");v.game.paused=false;for(int i=0;i<20/speed;i++){v.game.event=false;v.tick.run();}require(e.elapsedMinutes()==20,"same game time at 1/2/4");}
 }
 public static void main(String[]args){migrations();lifecycle(true);lifecycle(false);uiAndClock();System.out.println("PASS: "+checks+" STORY1.2 assertions; existing completed/unfinished saves, no-tick activation, three real map markers/routes, actual expedition failure/retry/return/once-only documents/key, all phases restored, sealed door, resumed compact dialogs, separate decisions, paused/speeds, preserved original plot and online data.");}
}
'''
def main():
 with tempfile.TemporaryDirectory(prefix='story12-') as directory:
  fixtures.PROBE=LEGACY
  old=fixtures.run_version(Path(directory),'story111',base.sources(OLD));blocks=[]
  for line in old.splitlines():
   if line=='SAVE':blocks.append([])
   elif line.startswith('VALUE:'):
    _,key,kind,value=line.split(':',3);value=base64.b64decode(value).decode();method={'Integer':'putInt','Boolean':'putBoolean','String':'putString'}[kind];literal=json.dumps(value,ensure_ascii=False) if kind=='String' else value;blocks[-1].append(f'e.{method}({json.dumps(key)}, {literal});')
  assert len(blocks)==4
  method=' static List<MemoryPreferences> legacy(){List<MemoryPreferences> result=new ArrayList<>();MemoryPreferences p;SharedPreferences.Editor e;'
  for block in blocks:method+='p=new MemoryPreferences();e=p.edit();'+''.join(block)+'e.commit();result.add(p);'
  method+='return result;}'
  fixtures.PROBE=PROBE.replace(' public static void main(String[]args){migrations()',method+' public static void main(String[]args){migrations()')
  try:print(fixtures.run_version(Path(directory),'investigation',base.sources()).strip())
  except __import__('subprocess').CalledProcessError as error:
   if error.output:print(error.output)
   raise
if __name__=='__main__':main()
